// Replace const commercialOrders = [...] in projects-content.tsx with this data

export const commercialOrdersData = [
  {
    "id": "COM-2024-001",
    "customer": "FAG Bearings",
    "job": "Packaging Boxes",
    "jdoId": "JDO-2024-042",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "prePressStatus": "In Progress",
    "productionStatus": "Scheduled",
    "dispatchStatus": "Pending",
    "amount": 4854602,
    "quantity": "16929 units",
    "status": "In Review",
    "orderDate": "2023-08-06",
    "expectedDelivery": "2023-11-16",
    "progress": 61,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-002",
    "customer": "Apollo Tyres",
    "job": "Tea/Coffee Packaging",
    "jdoId": "JDO-2024-048",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "prePressStatus": "In Progress",
    "productionStatus": "Released",
    "dispatchStatus": "Pending",
    "amount": 3873997,
    "quantity": "18617 units",
    "status": "Approved",
    "orderDate": "2023-10-26",
    "expectedDelivery": "2023-11-05",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-003",
    "customer": "Voltas Limited",
    "job": "Corrugated Sheets",
    "jdoId": "JDO-2024-071",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant A",
    "prePressStatus": "Scheduled",
    "productionStatus": "Released",
    "dispatchStatus": "Pending",
    "amount": 3493673,
    "quantity": "6199 units",
    "status": "In PDD",
    "orderDate": "2024-01-02",
    "expectedDelivery": "2024-02-17",
    "progress": 45,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-004",
    "customer": "JK Tyre",
    "job": "Auto Parts Packaging",
    "jdoId": "JDO-2024-122",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "prePressStatus": "Released",
    "productionStatus": "Released",
    "dispatchStatus": "Dispatched",
    "amount": 1576381,
    "quantity": "24772 units",
    "status": "In Review",
    "orderDate": "2024-01-06",
    "expectedDelivery": "2024-01-27",
    "progress": 90,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-005",
    "customer": "Hitachi India",
    "job": "Delivery Cartons",
    "jdoId": "JDO-2024-096",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "prePressStatus": "Complete",
    "productionStatus": "Pending",
    "dispatchStatus": "Scheduled",
    "amount": 4515319,
    "quantity": "42121 units",
    "status": "Approved",
    "orderDate": "2023-07-18",
    "expectedDelivery": "2023-09-15",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-006",
    "customer": "Crompton Greaves",
    "job": "Snack Packaging",
    "jdoId": "JDO-2024-130",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "prePressStatus": "Complete",
    "productionStatus": "Pending",
    "dispatchStatus": "Scheduled",
    "amount": 269479,
    "quantity": "31248 units",
    "status": "In Review",
    "orderDate": "2023-07-14",
    "expectedDelivery": "2023-09-13",
    "progress": 90,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-007",
    "customer": "ThyssenKrupp Elevators",
    "job": "Pharmaceutical Cartons",
    "jdoId": "JDO-2024-133",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "prePressStatus": "Approved",
    "productionStatus": "In Progress",
    "dispatchStatus": "Dispatched",
    "amount": 94362,
    "quantity": "45174 units",
    "status": "Approved",
    "orderDate": "2023-10-28",
    "expectedDelivery": "2023-12-20",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-008",
    "customer": "Havells India",
    "job": "Pharmaceutical Cartons",
    "jdoId": "JDO-2024-098",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "prePressStatus": "In PDD",
    "productionStatus": "Scheduled",
    "dispatchStatus": "Dispatched",
    "amount": 983622,
    "quantity": "49470 units",
    "status": "In Review",
    "orderDate": "2023-07-05",
    "expectedDelivery": "2023-12-11",
    "progress": 40,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-009",
    "customer": "TCS",
    "job": "Delivery Cartons",
    "jdoId": "JDO-2024-143",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "prePressStatus": "In Progress",
    "productionStatus": "Complete",
    "dispatchStatus": "Dispatched",
    "amount": 2481871,
    "quantity": "25097 units",
    "status": "In Review",
    "orderDate": "2023-09-29",
    "expectedDelivery": "2023-09-30",
    "progress": 86,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-010",
    "customer": "Dr Reddy's Labs",
    "job": "Delivery Cartons",
    "jdoId": "JDO-2024-093",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "prePressStatus": "Scheduled",
    "productionStatus": "Complete",
    "dispatchStatus": "Dispatched",
    "amount": 3260502,
    "quantity": "2233 units",
    "status": "In PDD",
    "orderDate": "2023-08-25",
    "expectedDelivery": "2023-11-23",
    "progress": 82,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-011",
    "customer": "Larsen & Toubro",
    "job": "Tea/Coffee Packaging",
    "jdoId": "JDO-2024-107",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "prePressStatus": "Complete",
    "productionStatus": "Pending",
    "dispatchStatus": "Pending",
    "amount": 1851723,
    "quantity": "11993 units",
    "status": "Approved",
    "orderDate": "2023-07-18",
    "expectedDelivery": "2023-09-24",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-012",
    "customer": "Crompton Greaves",
    "job": "Corrugated Sheets",
    "jdoId": "JDO-2024-004",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "prePressStatus": "In Progress",
    "productionStatus": "In PDD",
    "dispatchStatus": "Dispatched",
    "amount": 961552,
    "quantity": "27934 units",
    "status": "In Review",
    "orderDate": "2023-12-29",
    "expectedDelivery": "2024-02-17",
    "progress": 69,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-013",
    "customer": "Sony India",
    "job": "Electronic Device Boxes",
    "jdoId": "JDO-2024-046",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "prePressStatus": "In PDD",
    "productionStatus": "In Progress",
    "dispatchStatus": "Pending",
    "amount": 3539253,
    "quantity": "9483 units",
    "status": "In Review",
    "orderDate": "2023-12-07",
    "expectedDelivery": "2024-02-13",
    "progress": 80,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-014",
    "customer": "Gates India",
    "job": "Shipping Containers",
    "jdoId": "JDO-2024-018",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "prePressStatus": "Pending",
    "productionStatus": "Approved",
    "dispatchStatus": "Dispatched",
    "amount": 1436932,
    "quantity": "28507 units",
    "status": "In Review",
    "orderDate": "2023-10-23",
    "expectedDelivery": "2023-12-02",
    "progress": 77,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-015",
    "customer": "Otis Elevator",
    "job": "Medicine Cartons",
    "jdoId": "JDO-2024-060",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "prePressStatus": "Scheduled",
    "productionStatus": "In PDD",
    "dispatchStatus": "Scheduled",
    "amount": 883683,
    "quantity": "9975 units",
    "status": "Approved",
    "orderDate": "2023-08-13",
    "expectedDelivery": "2024-01-31",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-016",
    "customer": "Honeywell India",
    "job": "Industrial Labels",
    "jdoId": "JDO-2024-040",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "prePressStatus": "Pending",
    "productionStatus": "Scheduled",
    "dispatchStatus": "Scheduled",
    "amount": 4842798,
    "quantity": "29848 units",
    "status": "In Review",
    "orderDate": "2023-11-26",
    "expectedDelivery": "2024-02-24",
    "progress": 66,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-017",
    "customer": "ABB India",
    "job": "Printed Labels",
    "jdoId": "JDO-2024-059",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "prePressStatus": "In PDD",
    "productionStatus": "Complete",
    "dispatchStatus": "Dispatched",
    "amount": 4751389,
    "quantity": "22641 units",
    "status": "In PDD",
    "orderDate": "2024-01-01",
    "expectedDelivery": "2024-02-15",
    "progress": 50,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-018",
    "customer": "Coca-Cola India",
    "job": "Luxury Gift Boxes",
    "jdoId": "JDO-2024-065",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "prePressStatus": "In Progress",
    "productionStatus": "In Progress",
    "dispatchStatus": "Dispatched",
    "amount": 349726,
    "quantity": "2518 units",
    "status": "In Review",
    "orderDate": "2023-07-10",
    "expectedDelivery": "2023-09-05",
    "progress": 60,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-019",
    "customer": "Blue Star",
    "job": "Delivery Cartons",
    "jdoId": "JDO-2024-015",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "prePressStatus": "In PDD",
    "productionStatus": "In Progress",
    "dispatchStatus": "Pending",
    "amount": 3554309,
    "quantity": "40854 units",
    "status": "Approved",
    "orderDate": "2023-12-07",
    "expectedDelivery": "2024-02-02",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-020",
    "customer": "JK Tyre",
    "job": "Die-Cut Boxes",
    "jdoId": "JDO-2024-026",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "prePressStatus": "Released",
    "productionStatus": "In Progress",
    "dispatchStatus": "Dispatched",
    "amount": 3061873,
    "quantity": "33905 units",
    "status": "In Review",
    "orderDate": "2023-06-30",
    "expectedDelivery": "2023-10-03",
    "progress": 87,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-021",
    "customer": "Sun Pharma",
    "job": "Medicine Cartons",
    "jdoId": "JDO-2024-020",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "prePressStatus": "In Progress",
    "productionStatus": "In Progress",
    "dispatchStatus": "Dispatched",
    "amount": 2033976,
    "quantity": "28722 units",
    "status": "Approved",
    "orderDate": "2023-08-17",
    "expectedDelivery": "2023-12-19",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-022",
    "customer": "Blue Star",
    "job": "Food Grade Packaging",
    "jdoId": "JDO-2024-088",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "prePressStatus": "Released",
    "productionStatus": "Complete",
    "dispatchStatus": "Pending",
    "amount": 329918,
    "quantity": "38119 units",
    "status": "In PDD",
    "orderDate": "2023-11-05",
    "expectedDelivery": "2023-12-12",
    "progress": 58,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-023",
    "customer": "Schindler India",
    "job": "Industrial Labels",
    "jdoId": "JDO-2024-097",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "prePressStatus": "Scheduled",
    "productionStatus": "Scheduled",
    "dispatchStatus": "Pending",
    "amount": 1512691,
    "quantity": "37265 units",
    "status": "Approved",
    "orderDate": "2023-06-29",
    "expectedDelivery": "2024-01-30",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-024",
    "customer": "PepsiCo India",
    "job": "Tea/Coffee Packaging",
    "jdoId": "JDO-2024-075",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "prePressStatus": "Scheduled",
    "productionStatus": "Complete",
    "dispatchStatus": "Dispatched",
    "amount": 2739547,
    "quantity": "31976 units",
    "status": "In Review",
    "orderDate": "2023-10-11",
    "expectedDelivery": "2023-11-16",
    "progress": 65,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-025",
    "customer": "Ceat Tyres",
    "job": "Pharmaceutical Cartons",
    "jdoId": "JDO-2024-010",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "prePressStatus": "Pending",
    "productionStatus": "Complete",
    "dispatchStatus": "Dispatched",
    "amount": 3770239,
    "quantity": "33788 units",
    "status": "Approved",
    "orderDate": "2023-12-22",
    "expectedDelivery": "2024-01-26",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-026",
    "customer": "Hindalco Industries",
    "job": "Luxury Gift Boxes",
    "jdoId": "JDO-2024-045",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "prePressStatus": "Approved",
    "productionStatus": "Released",
    "dispatchStatus": "Dispatched",
    "amount": 3633126,
    "quantity": "40325 units",
    "status": "Approved",
    "orderDate": "2023-09-24",
    "expectedDelivery": "2024-01-22",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-027",
    "customer": "Parle Products",
    "job": "Auto Parts Packaging",
    "jdoId": "JDO-2024-101",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant A",
    "prePressStatus": "Complete",
    "productionStatus": "In PDD",
    "dispatchStatus": "Scheduled",
    "amount": 4028812,
    "quantity": "43941 units",
    "status": "In PDD",
    "orderDate": "2023-10-16",
    "expectedDelivery": "2023-11-28",
    "progress": 67,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-028",
    "customer": "Dr Reddy's Labs",
    "job": "Die-Cut Boxes",
    "jdoId": "JDO-2024-107",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "prePressStatus": "In Progress",
    "productionStatus": "Scheduled",
    "dispatchStatus": "Dispatched",
    "amount": 2121189,
    "quantity": "9218 units",
    "status": "In PDD",
    "orderDate": "2023-06-21",
    "expectedDelivery": "2023-07-19",
    "progress": 60,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-029",
    "customer": "Britannia Industries",
    "job": "Folding Cartons",
    "jdoId": "JDO-2024-059",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "prePressStatus": "Released",
    "productionStatus": "Released",
    "dispatchStatus": "Scheduled",
    "amount": 80915,
    "quantity": "13446 units",
    "status": "Approved",
    "orderDate": "2023-07-11",
    "expectedDelivery": "2023-07-19",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-030",
    "customer": "Butterfly Gandhimathi",
    "job": "Electronic Device Boxes",
    "jdoId": "JDO-2024-008",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "prePressStatus": "Complete",
    "productionStatus": "Released",
    "dispatchStatus": "Dispatched",
    "amount": 1480638,
    "quantity": "13558 units",
    "status": "In PDD",
    "orderDate": "2023-12-02",
    "expectedDelivery": "2024-01-03",
    "progress": 90,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-031",
    "customer": "Crompton Greaves",
    "job": "Delivery Cartons",
    "jdoId": "JDO-2024-044",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "prePressStatus": "Approved",
    "productionStatus": "Pending",
    "dispatchStatus": "Dispatched",
    "amount": 1587525,
    "quantity": "20495 units",
    "status": "In Review",
    "orderDate": "2023-08-05",
    "expectedDelivery": "2023-11-27",
    "progress": 46,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-032",
    "customer": "Amazon India",
    "job": "Beverage Cartons",
    "jdoId": "JDO-2024-139",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "prePressStatus": "Released",
    "productionStatus": "In PDD",
    "dispatchStatus": "Pending",
    "amount": 328889,
    "quantity": "37997 units",
    "status": "In PDD",
    "orderDate": "2023-06-16",
    "expectedDelivery": "2023-11-02",
    "progress": 45,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-033",
    "customer": "Parle Products",
    "job": "Industrial Labels",
    "jdoId": "JDO-2024-046",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "prePressStatus": "Complete",
    "productionStatus": "In Progress",
    "dispatchStatus": "Pending",
    "amount": 4698960,
    "quantity": "41145 units",
    "status": "In Review",
    "orderDate": "2023-07-21",
    "expectedDelivery": "2023-07-27",
    "progress": 95,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-034",
    "customer": "Britannia Industries",
    "job": "Cosmetic Packaging",
    "jdoId": "JDO-2024-077",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "prePressStatus": "Released",
    "productionStatus": "Pending",
    "dispatchStatus": "Dispatched",
    "amount": 1104325,
    "quantity": "8406 units",
    "status": "In Review",
    "orderDate": "2023-11-10",
    "expectedDelivery": "2024-01-25",
    "progress": 59,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-035",
    "customer": "Gates India",
    "job": "Tea/Coffee Packaging",
    "jdoId": "JDO-2024-021",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "prePressStatus": "Complete",
    "productionStatus": "Released",
    "dispatchStatus": "Dispatched",
    "amount": 2643100,
    "quantity": "17374 units",
    "status": "Approved",
    "orderDate": "2023-12-16",
    "expectedDelivery": "2024-02-05",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-036",
    "customer": "Blue Star",
    "job": "Appliance Cartons",
    "jdoId": "JDO-2024-110",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "prePressStatus": "In Progress",
    "productionStatus": "Complete",
    "dispatchStatus": "Scheduled",
    "amount": 2244046,
    "quantity": "4588 units",
    "status": "In Review",
    "orderDate": "2023-08-18",
    "expectedDelivery": "2023-08-24",
    "progress": 63,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-037",
    "customer": "Big Bazaar",
    "job": "Packaging Boxes",
    "jdoId": "JDO-2024-106",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "prePressStatus": "Approved",
    "productionStatus": "Released",
    "dispatchStatus": "Pending",
    "amount": 3747201,
    "quantity": "1877 units",
    "status": "Approved",
    "orderDate": "2023-12-03",
    "expectedDelivery": "2024-01-27",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-038",
    "customer": "Pigeon India",
    "job": "Appliance Cartons",
    "jdoId": "JDO-2024-093",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "prePressStatus": "Complete",
    "productionStatus": "In Progress",
    "dispatchStatus": "Pending",
    "amount": 3271465,
    "quantity": "22068 units",
    "status": "In PDD",
    "orderDate": "2023-06-04",
    "expectedDelivery": "2023-09-19",
    "progress": 66,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-039",
    "customer": "NSK India",
    "job": "Shipping Containers",
    "jdoId": "JDO-2024-033",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "prePressStatus": "Pending",
    "productionStatus": "Pending",
    "dispatchStatus": "Scheduled",
    "amount": 908444,
    "quantity": "6440 units",
    "status": "Approved",
    "orderDate": "2023-11-10",
    "expectedDelivery": "2023-11-12",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-040",
    "customer": "Coca-Cola India",
    "job": "Packaging Boxes",
    "jdoId": "JDO-2024-083",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "prePressStatus": "Scheduled",
    "productionStatus": "Pending",
    "dispatchStatus": "Pending",
    "amount": 817741,
    "quantity": "40893 units",
    "status": "In Review",
    "orderDate": "2023-08-31",
    "expectedDelivery": "2023-10-06",
    "progress": 82,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-041",
    "customer": "FAG Bearings",
    "job": "Food Grade Packaging",
    "jdoId": "JDO-2024-001",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "prePressStatus": "Released",
    "productionStatus": "Released",
    "dispatchStatus": "Pending",
    "amount": 2756249,
    "quantity": "43825 units",
    "status": "Approved",
    "orderDate": "2023-12-10",
    "expectedDelivery": "2023-12-21",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-042",
    "customer": "Carrier Midea India",
    "job": "Packaging Boxes",
    "jdoId": "JDO-2024-122",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "prePressStatus": "Approved",
    "productionStatus": "Scheduled",
    "dispatchStatus": "Dispatched",
    "amount": 4122986,
    "quantity": "17111 units",
    "status": "In Review",
    "orderDate": "2023-06-20",
    "expectedDelivery": "2024-01-07",
    "progress": 57,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-043",
    "customer": "Reebok India",
    "job": "Food Grade Packaging",
    "jdoId": "JDO-2024-028",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "prePressStatus": "Scheduled",
    "productionStatus": "In PDD",
    "dispatchStatus": "Pending",
    "amount": 497383,
    "quantity": "42305 units",
    "status": "In Review",
    "orderDate": "2023-11-08",
    "expectedDelivery": "2024-02-17",
    "progress": 64,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-044",
    "customer": "Legrand India",
    "job": "Medicine Cartons",
    "jdoId": "JDO-2024-064",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "prePressStatus": "In Progress",
    "productionStatus": "Approved",
    "dispatchStatus": "Pending",
    "amount": 2570360,
    "quantity": "23105 units",
    "status": "Approved",
    "orderDate": "2023-12-18",
    "expectedDelivery": "2023-12-26",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-045",
    "customer": "PepsiCo India",
    "job": "Pharmaceutical Cartons",
    "jdoId": "JDO-2024-044",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "prePressStatus": "In Progress",
    "productionStatus": "Pending",
    "dispatchStatus": "Scheduled",
    "amount": 3746232,
    "quantity": "45501 units",
    "status": "In PDD",
    "orderDate": "2023-11-26",
    "expectedDelivery": "2024-01-03",
    "progress": 51,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-046",
    "customer": "ITC Limited",
    "job": "Tea/Coffee Packaging",
    "jdoId": "JDO-2024-040",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "prePressStatus": "In PDD",
    "productionStatus": "In Progress",
    "dispatchStatus": "Pending",
    "amount": 3271597,
    "quantity": "36202 units",
    "status": "Approved",
    "orderDate": "2023-06-13",
    "expectedDelivery": "2023-06-22",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-047",
    "customer": "Cipla Pharmaceuticals",
    "job": "Snack Packaging",
    "jdoId": "JDO-2024-107",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "prePressStatus": "Scheduled",
    "productionStatus": "In PDD",
    "dispatchStatus": "Pending",
    "amount": 435626,
    "quantity": "39617 units",
    "status": "In Review",
    "orderDate": "2023-09-06",
    "expectedDelivery": "2023-11-08",
    "progress": 94,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-048",
    "customer": "Nestle India",
    "job": "Folding Cartons",
    "jdoId": "JDO-2024-034",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "prePressStatus": "Released",
    "productionStatus": "In Progress",
    "dispatchStatus": "Dispatched",
    "amount": 1910469,
    "quantity": "41432 units",
    "status": "In PDD",
    "orderDate": "2023-08-24",
    "expectedDelivery": "2023-12-06",
    "progress": 94,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-049",
    "customer": "Amul",
    "job": "Corrugated Sheets",
    "jdoId": "JDO-2024-042",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "prePressStatus": "Complete",
    "productionStatus": "Scheduled",
    "dispatchStatus": "Pending",
    "amount": 4057215,
    "quantity": "46894 units",
    "status": "In PDD",
    "orderDate": "2023-12-28",
    "expectedDelivery": "2024-02-22",
    "progress": 87,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-050",
    "customer": "Britannia Industries",
    "job": "Shipping Containers",
    "jdoId": "JDO-2024-139",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "prePressStatus": "Released",
    "productionStatus": "Approved",
    "dispatchStatus": "Dispatched",
    "amount": 561563,
    "quantity": "23472 units",
    "status": "In PDD",
    "orderDate": "2023-08-20",
    "expectedDelivery": "2024-02-27",
    "progress": 69,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-051",
    "customer": "Vedanta Limited",
    "job": "Printed Labels",
    "jdoId": "JDO-2024-111",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "prePressStatus": "In PDD",
    "productionStatus": "In Progress",
    "dispatchStatus": "Scheduled",
    "amount": 4850859,
    "quantity": "40590 units",
    "status": "In Review",
    "orderDate": "2023-07-22",
    "expectedDelivery": "2023-11-17",
    "progress": 78,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-052",
    "customer": "JK Tyre",
    "job": "Industrial Labels",
    "jdoId": "JDO-2024-117",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "prePressStatus": "In PDD",
    "productionStatus": "Pending",
    "dispatchStatus": "Dispatched",
    "amount": 4425714,
    "quantity": "48982 units",
    "status": "In PDD",
    "orderDate": "2023-06-21",
    "expectedDelivery": "2023-09-20",
    "progress": 44,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-053",
    "customer": "Kone India",
    "job": "Medicine Cartons",
    "jdoId": "JDO-2024-122",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "prePressStatus": "Approved",
    "productionStatus": "Scheduled",
    "dispatchStatus": "Scheduled",
    "amount": 3423829,
    "quantity": "47930 units",
    "status": "In PDD",
    "orderDate": "2023-06-27",
    "expectedDelivery": "2024-02-16",
    "progress": 54,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-054",
    "customer": "BigBasket",
    "job": "Auto Parts Packaging",
    "jdoId": "JDO-2024-025",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "prePressStatus": "Complete",
    "productionStatus": "Scheduled",
    "dispatchStatus": "Dispatched",
    "amount": 1781161,
    "quantity": "43837 units",
    "status": "Approved",
    "orderDate": "2023-06-02",
    "expectedDelivery": "2023-11-14",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-055",
    "customer": "DMart",
    "job": "E-commerce Shipping Boxes",
    "jdoId": "JDO-2024-072",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "prePressStatus": "Pending",
    "productionStatus": "In PDD",
    "dispatchStatus": "Dispatched",
    "amount": 1370932,
    "quantity": "37031 units",
    "status": "In PDD",
    "orderDate": "2023-11-11",
    "expectedDelivery": "2024-01-04",
    "progress": 58,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-056",
    "customer": "Larsen & Toubro",
    "job": "Food Grade Packaging",
    "jdoId": "JDO-2024-094",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "prePressStatus": "Scheduled",
    "productionStatus": "Pending",
    "dispatchStatus": "Pending",
    "amount": 2392155,
    "quantity": "34997 units",
    "status": "In Review",
    "orderDate": "2023-07-23",
    "expectedDelivery": "2024-02-02",
    "progress": 43,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-057",
    "customer": "BHEL India",
    "job": "E-commerce Shipping Boxes",
    "jdoId": "JDO-2024-021",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "prePressStatus": "Released",
    "productionStatus": "In Progress",
    "dispatchStatus": "Dispatched",
    "amount": 1191565,
    "quantity": "16039 units",
    "status": "In PDD",
    "orderDate": "2023-11-30",
    "expectedDelivery": "2023-12-28",
    "progress": 65,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-058",
    "customer": "Havells India",
    "job": "Shipping Containers",
    "jdoId": "JDO-2024-119",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "prePressStatus": "Released",
    "productionStatus": "Released",
    "dispatchStatus": "Pending",
    "amount": 2433189,
    "quantity": "40580 units",
    "status": "Approved",
    "orderDate": "2023-08-31",
    "expectedDelivery": "2023-10-10",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-059",
    "customer": "Vadilal Industries",
    "job": "Folding Cartons",
    "jdoId": "JDO-2024-087",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "prePressStatus": "Approved",
    "productionStatus": "Pending",
    "dispatchStatus": "Pending",
    "amount": 412811,
    "quantity": "13855 units",
    "status": "Approved",
    "orderDate": "2023-09-20",
    "expectedDelivery": "2023-10-22",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-060",
    "customer": "Sony India",
    "job": "Retail Display Boxes",
    "jdoId": "JDO-2024-023",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "prePressStatus": "In PDD",
    "productionStatus": "In PDD",
    "dispatchStatus": "Pending",
    "amount": 3797943,
    "quantity": "20599 units",
    "status": "Approved",
    "orderDate": "2023-08-08",
    "expectedDelivery": "2024-01-08",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-061",
    "customer": "Havells India",
    "job": "Cosmetic Packaging",
    "jdoId": "JDO-2024-087",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "prePressStatus": "Pending",
    "productionStatus": "Complete",
    "dispatchStatus": "Pending",
    "amount": 3113414,
    "quantity": "32861 units",
    "status": "In Review",
    "orderDate": "2023-07-04",
    "expectedDelivery": "2023-08-19",
    "progress": 75,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-062",
    "customer": "LG Electronics",
    "job": "Printed Labels",
    "jdoId": "JDO-2024-141",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "prePressStatus": "Complete",
    "productionStatus": "Released",
    "dispatchStatus": "Pending",
    "amount": 429139,
    "quantity": "4766 units",
    "status": "Approved",
    "orderDate": "2023-08-15",
    "expectedDelivery": "2023-09-03",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-063",
    "customer": "Cummins India",
    "job": "Industrial Labels",
    "jdoId": "JDO-2024-062",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "prePressStatus": "Complete",
    "productionStatus": "In PDD",
    "dispatchStatus": "Pending",
    "amount": 3024748,
    "quantity": "8531 units",
    "status": "In Review",
    "orderDate": "2023-08-08",
    "expectedDelivery": "2023-10-06",
    "progress": 48,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-064",
    "customer": "Hitachi India",
    "job": "Corrugated Sheets",
    "jdoId": "JDO-2024-041",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "prePressStatus": "Approved",
    "productionStatus": "Complete",
    "dispatchStatus": "Scheduled",
    "amount": 4602698,
    "quantity": "16110 units",
    "status": "Approved",
    "orderDate": "2023-08-10",
    "expectedDelivery": "2023-12-15",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-065",
    "customer": "GE India",
    "job": "Folding Cartons",
    "jdoId": "JDO-2024-098",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant A",
    "prePressStatus": "Complete",
    "productionStatus": "In Progress",
    "dispatchStatus": "Dispatched",
    "amount": 752353,
    "quantity": "3938 units",
    "status": "Approved",
    "orderDate": "2023-08-20",
    "expectedDelivery": "2024-01-12",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-066",
    "customer": "Otis Elevator",
    "job": "Industrial Labels",
    "jdoId": "JDO-2024-011",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "prePressStatus": "Complete",
    "productionStatus": "Released",
    "dispatchStatus": "Scheduled",
    "amount": 3015524,
    "quantity": "36055 units",
    "status": "In PDD",
    "orderDate": "2023-06-30",
    "expectedDelivery": "2024-01-02",
    "progress": 52,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-067",
    "customer": "Voltas Limited",
    "job": "Appliance Cartons",
    "jdoId": "JDO-2024-081",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "prePressStatus": "In Progress",
    "productionStatus": "Approved",
    "dispatchStatus": "Scheduled",
    "amount": 2838049,
    "quantity": "17244 units",
    "status": "In Review",
    "orderDate": "2023-08-04",
    "expectedDelivery": "2024-02-21",
    "progress": 62,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-068",
    "customer": "BigBasket",
    "job": "E-commerce Shipping Boxes",
    "jdoId": "JDO-2024-011",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "prePressStatus": "Scheduled",
    "productionStatus": "Complete",
    "dispatchStatus": "Scheduled",
    "amount": 1262551,
    "quantity": "17246 units",
    "status": "In PDD",
    "orderDate": "2023-06-17",
    "expectedDelivery": "2023-09-19",
    "progress": 66,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-069",
    "customer": "Kwality Walls",
    "job": "Industrial Labels",
    "jdoId": "JDO-2024-083",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "prePressStatus": "Complete",
    "productionStatus": "Complete",
    "dispatchStatus": "Scheduled",
    "amount": 3284371,
    "quantity": "49134 units",
    "status": "In PDD",
    "orderDate": "2023-10-19",
    "expectedDelivery": "2024-01-01",
    "progress": 57,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-070",
    "customer": "Schindler India",
    "job": "Auto Parts Packaging",
    "jdoId": "JDO-2024-035",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "prePressStatus": "Complete",
    "productionStatus": "Approved",
    "dispatchStatus": "Scheduled",
    "amount": 4541645,
    "quantity": "35123 units",
    "status": "Approved",
    "orderDate": "2023-12-22",
    "expectedDelivery": "2024-01-19",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-071",
    "customer": "Blue Star",
    "job": "Shipping Containers",
    "jdoId": "JDO-2024-025",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "prePressStatus": "Scheduled",
    "productionStatus": "Scheduled",
    "dispatchStatus": "Dispatched",
    "amount": 2278344,
    "quantity": "28007 units",
    "status": "In PDD",
    "orderDate": "2023-10-04",
    "expectedDelivery": "2023-10-05",
    "progress": 76,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-072",
    "customer": "BHEL India",
    "job": "Food Grade Packaging",
    "jdoId": "JDO-2024-038",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "prePressStatus": "Released",
    "productionStatus": "Approved",
    "dispatchStatus": "Pending",
    "amount": 2650355,
    "quantity": "45271 units",
    "status": "In Review",
    "orderDate": "2023-06-17",
    "expectedDelivery": "2023-07-28",
    "progress": 56,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-073",
    "customer": "Hero MotoCorp",
    "job": "Snack Packaging",
    "jdoId": "JDO-2024-001",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "prePressStatus": "In Progress",
    "productionStatus": "Scheduled",
    "dispatchStatus": "Dispatched",
    "amount": 1916726,
    "quantity": "6721 units",
    "status": "Approved",
    "orderDate": "2023-09-22",
    "expectedDelivery": "2024-02-17",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-074",
    "customer": "Flipkart",
    "job": "Snack Packaging",
    "jdoId": "JDO-2024-020",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "prePressStatus": "Released",
    "productionStatus": "Released",
    "dispatchStatus": "Scheduled",
    "amount": 3637907,
    "quantity": "9099 units",
    "status": "Approved",
    "orderDate": "2023-10-17",
    "expectedDelivery": "2024-01-20",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-075",
    "customer": "Otis Elevator",
    "job": "Snack Packaging",
    "jdoId": "JDO-2024-117",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "prePressStatus": "Pending",
    "productionStatus": "Released",
    "dispatchStatus": "Dispatched",
    "amount": 798988,
    "quantity": "10873 units",
    "status": "In Review",
    "orderDate": "2023-10-01",
    "expectedDelivery": "2023-12-04",
    "progress": 91,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-076",
    "customer": "Blue Star",
    "job": "Corrugated Sheets",
    "jdoId": "JDO-2024-127",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "prePressStatus": "In Progress",
    "productionStatus": "Complete",
    "dispatchStatus": "Scheduled",
    "amount": 3588292,
    "quantity": "2538 units",
    "status": "In Review",
    "orderDate": "2023-12-14",
    "expectedDelivery": "2024-01-27",
    "progress": 62,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-077",
    "customer": "ThyssenKrupp Elevators",
    "job": "Industrial Labels",
    "jdoId": "JDO-2024-098",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "prePressStatus": "In PDD",
    "productionStatus": "Approved",
    "dispatchStatus": "Pending",
    "amount": 3058947,
    "quantity": "2797 units",
    "status": "In Review",
    "orderDate": "2023-06-21",
    "expectedDelivery": "2023-09-17",
    "progress": 46,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-078",
    "customer": "Legrand India",
    "job": "Retail Display Boxes",
    "jdoId": "JDO-2024-063",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "prePressStatus": "In PDD",
    "productionStatus": "Complete",
    "dispatchStatus": "Dispatched",
    "amount": 2473442,
    "quantity": "21184 units",
    "status": "In Review",
    "orderDate": "2023-08-23",
    "expectedDelivery": "2023-10-05",
    "progress": 83,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-079",
    "customer": "Megadyne India",
    "job": "Food Grade Packaging",
    "jdoId": "JDO-2024-117",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "prePressStatus": "Scheduled",
    "productionStatus": "In Progress",
    "dispatchStatus": "Scheduled",
    "amount": 3446977,
    "quantity": "12852 units",
    "status": "Approved",
    "orderDate": "2023-12-28",
    "expectedDelivery": "2024-01-28",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-080",
    "customer": "Ceat Tyres",
    "job": "Electronic Device Boxes",
    "jdoId": "JDO-2024-064",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "prePressStatus": "In PDD",
    "productionStatus": "Released",
    "dispatchStatus": "Pending",
    "amount": 3745454,
    "quantity": "38231 units",
    "status": "In Review",
    "orderDate": "2023-11-02",
    "expectedDelivery": "2023-11-12",
    "progress": 93,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-081",
    "customer": "Fenner India",
    "job": "Electronic Device Boxes",
    "jdoId": "JDO-2024-133",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "prePressStatus": "Pending",
    "productionStatus": "Released",
    "dispatchStatus": "Pending",
    "amount": 384337,
    "quantity": "29939 units",
    "status": "In PDD",
    "orderDate": "2023-10-22",
    "expectedDelivery": "2024-02-13",
    "progress": 74,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-082",
    "customer": "Vadilal Industries",
    "job": "Luxury Gift Boxes",
    "jdoId": "JDO-2024-093",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "prePressStatus": "Complete",
    "productionStatus": "Approved",
    "dispatchStatus": "Pending",
    "amount": 3198311,
    "quantity": "3633 units",
    "status": "In Review",
    "orderDate": "2023-12-11",
    "expectedDelivery": "2024-02-15",
    "progress": 71,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-083",
    "customer": "Reebok India",
    "job": "Cosmetic Packaging",
    "jdoId": "JDO-2024-114",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "prePressStatus": "Pending",
    "productionStatus": "Pending",
    "dispatchStatus": "Pending",
    "amount": 354648,
    "quantity": "11033 units",
    "status": "In PDD",
    "orderDate": "2023-10-17",
    "expectedDelivery": "2023-11-22",
    "progress": 76,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-084",
    "customer": "Decathlon India",
    "job": "Tea/Coffee Packaging",
    "jdoId": "JDO-2024-069",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "prePressStatus": "Approved",
    "productionStatus": "Approved",
    "dispatchStatus": "Dispatched",
    "amount": 2135657,
    "quantity": "4638 units",
    "status": "Approved",
    "orderDate": "2023-07-19",
    "expectedDelivery": "2023-07-20",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-085",
    "customer": "SKF India",
    "job": "Shipping Containers",
    "jdoId": "JDO-2024-021",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "prePressStatus": "Released",
    "productionStatus": "Approved",
    "dispatchStatus": "Pending",
    "amount": 3229870,
    "quantity": "14430 units",
    "status": "In Review",
    "orderDate": "2023-12-25",
    "expectedDelivery": "2024-01-21",
    "progress": 64,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-086",
    "customer": "Flipkart",
    "job": "Shipping Containers",
    "jdoId": "JDO-2024-129",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "prePressStatus": "Pending",
    "productionStatus": "Scheduled",
    "dispatchStatus": "Scheduled",
    "amount": 2220892,
    "quantity": "19958 units",
    "status": "In Review",
    "orderDate": "2023-10-13",
    "expectedDelivery": "2024-02-19",
    "progress": 53,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-087",
    "customer": "Apollo Tyres",
    "job": "Food Grade Packaging",
    "jdoId": "JDO-2024-130",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "prePressStatus": "Scheduled",
    "productionStatus": "Scheduled",
    "dispatchStatus": "Pending",
    "amount": 3947694,
    "quantity": "13458 units",
    "status": "In Review",
    "orderDate": "2023-12-27",
    "expectedDelivery": "2024-01-02",
    "progress": 46,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-088",
    "customer": "Bisleri",
    "job": "Packaging Boxes",
    "jdoId": "JDO-2024-098",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "prePressStatus": "Scheduled",
    "productionStatus": "In PDD",
    "dispatchStatus": "Pending",
    "amount": 2977882,
    "quantity": "25811 units",
    "status": "Approved",
    "orderDate": "2023-07-27",
    "expectedDelivery": "2023-11-23",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-089",
    "customer": "TCS",
    "job": "Industrial Labels",
    "jdoId": "JDO-2024-093",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "prePressStatus": "In Progress",
    "productionStatus": "Complete",
    "dispatchStatus": "Dispatched",
    "amount": 2718338,
    "quantity": "23224 units",
    "status": "In PDD",
    "orderDate": "2023-06-18",
    "expectedDelivery": "2024-01-07",
    "progress": 52,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-090",
    "customer": "Cipla Pharmaceuticals",
    "job": "Appliance Cartons",
    "jdoId": "JDO-2024-117",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "prePressStatus": "In Progress",
    "productionStatus": "Pending",
    "dispatchStatus": "Scheduled",
    "amount": 533369,
    "quantity": "36968 units",
    "status": "In PDD",
    "orderDate": "2023-07-21",
    "expectedDelivery": "2023-12-02",
    "progress": 58,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-091",
    "customer": "Reebok India",
    "job": "Medicine Cartons",
    "jdoId": "JDO-2024-044",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "prePressStatus": "Approved",
    "productionStatus": "Approved",
    "dispatchStatus": "Pending",
    "amount": 288163,
    "quantity": "49303 units",
    "status": "In PDD",
    "orderDate": "2023-06-23",
    "expectedDelivery": "2024-02-11",
    "progress": 56,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-092",
    "customer": "Flipkart",
    "job": "Snack Packaging",
    "jdoId": "JDO-2024-067",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "prePressStatus": "Complete",
    "productionStatus": "Released",
    "dispatchStatus": "Scheduled",
    "amount": 2435838,
    "quantity": "32588 units",
    "status": "In Review",
    "orderDate": "2023-07-22",
    "expectedDelivery": "2023-09-06",
    "progress": 50,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-093",
    "customer": "Dabur India",
    "job": "Food Grade Packaging",
    "jdoId": "JDO-2024-126",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "prePressStatus": "Approved",
    "productionStatus": "Approved",
    "dispatchStatus": "Pending",
    "amount": 505059,
    "quantity": "4052 units",
    "status": "Approved",
    "orderDate": "2023-11-24",
    "expectedDelivery": "2023-12-18",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-094",
    "customer": "Reliance Retail",
    "job": "Delivery Cartons",
    "jdoId": "JDO-2024-126",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "prePressStatus": "In PDD",
    "productionStatus": "Approved",
    "dispatchStatus": "Dispatched",
    "amount": 3331066,
    "quantity": "22695 units",
    "status": "Approved",
    "orderDate": "2023-08-12",
    "expectedDelivery": "2024-02-03",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-095",
    "customer": "Blue Star",
    "job": "Delivery Cartons",
    "jdoId": "JDO-2024-128",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "prePressStatus": "Released",
    "productionStatus": "In PDD",
    "dispatchStatus": "Pending",
    "amount": 58039,
    "quantity": "23382 units",
    "status": "Approved",
    "orderDate": "2023-11-06",
    "expectedDelivery": "2023-12-24",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-096",
    "customer": "Flipkart",
    "job": "E-commerce Shipping Boxes",
    "jdoId": "JDO-2024-118",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "prePressStatus": "In PDD",
    "productionStatus": "Scheduled",
    "dispatchStatus": "Pending",
    "amount": 2798607,
    "quantity": "26981 units",
    "status": "In Review",
    "orderDate": "2023-11-01",
    "expectedDelivery": "2023-12-10",
    "progress": 89,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-097",
    "customer": "Kirloskar Electric",
    "job": "Appliance Cartons",
    "jdoId": "JDO-2024-039",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "prePressStatus": "In PDD",
    "productionStatus": "In Progress",
    "dispatchStatus": "Pending",
    "amount": 3943275,
    "quantity": "10224 units",
    "status": "In Review",
    "orderDate": "2023-10-22",
    "expectedDelivery": "2023-10-30",
    "progress": 67,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-098",
    "customer": "Dr Reddy's Labs",
    "job": "Medicine Cartons",
    "jdoId": "JDO-2024-117",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "prePressStatus": "In Progress",
    "productionStatus": "Scheduled",
    "dispatchStatus": "Dispatched",
    "amount": 2831165,
    "quantity": "13915 units",
    "status": "In PDD",
    "orderDate": "2023-09-22",
    "expectedDelivery": "2023-12-28",
    "progress": 72,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-099",
    "customer": "Schindler India",
    "job": "Retail Display Boxes",
    "jdoId": "JDO-2024-102",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant A",
    "prePressStatus": "Complete",
    "productionStatus": "Released",
    "dispatchStatus": "Dispatched",
    "amount": 2521968,
    "quantity": "6230 units",
    "status": "In PDD",
    "orderDate": "2023-07-06",
    "expectedDelivery": "2023-11-28",
    "progress": 57,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-100",
    "customer": "Bosch India",
    "job": "Electronic Device Boxes",
    "jdoId": "JDO-2024-027",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "prePressStatus": "Pending",
    "productionStatus": "Scheduled",
    "dispatchStatus": "Pending",
    "amount": 1323726,
    "quantity": "8195 units",
    "status": "In Review",
    "orderDate": "2023-12-14",
    "expectedDelivery": "2023-12-20",
    "progress": 66,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-101",
    "customer": "Aditya Birla Group",
    "job": "Food Grade Packaging",
    "jdoId": "JDO-2024-139",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "prePressStatus": "Released",
    "productionStatus": "Approved",
    "dispatchStatus": "Dispatched",
    "amount": 685905,
    "quantity": "6603 units",
    "status": "In PDD",
    "orderDate": "2023-12-17",
    "expectedDelivery": "2024-02-22",
    "progress": 95,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-102",
    "customer": "Voltas Limited",
    "job": "Pharmaceutical Cartons",
    "jdoId": "JDO-2024-068",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "prePressStatus": "Released",
    "productionStatus": "In Progress",
    "dispatchStatus": "Pending",
    "amount": 2100514,
    "quantity": "13347 units",
    "status": "In PDD",
    "orderDate": "2023-12-03",
    "expectedDelivery": "2024-02-19",
    "progress": 91,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-103",
    "customer": "NSK India",
    "job": "Electronic Device Boxes",
    "jdoId": "JDO-2024-107",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant A",
    "prePressStatus": "In PDD",
    "productionStatus": "Approved",
    "dispatchStatus": "Scheduled",
    "amount": 825625,
    "quantity": "10172 units",
    "status": "In PDD",
    "orderDate": "2023-09-12",
    "expectedDelivery": "2023-11-02",
    "progress": 84,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-104",
    "customer": "Red Bull India",
    "job": "Folding Cartons",
    "jdoId": "JDO-2024-064",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "prePressStatus": "Scheduled",
    "productionStatus": "Approved",
    "dispatchStatus": "Scheduled",
    "amount": 2245541,
    "quantity": "38581 units",
    "status": "Approved",
    "orderDate": "2023-07-10",
    "expectedDelivery": "2023-10-15",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-105",
    "customer": "Optibelt India",
    "job": "Pharmaceutical Cartons",
    "jdoId": "JDO-2024-059",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "prePressStatus": "Released",
    "productionStatus": "Approved",
    "dispatchStatus": "Scheduled",
    "amount": 475566,
    "quantity": "13534 units",
    "status": "Approved",
    "orderDate": "2023-07-04",
    "expectedDelivery": "2024-02-27",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-106",
    "customer": "LG Electronics",
    "job": "Pharmaceutical Cartons",
    "jdoId": "JDO-2024-129",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "prePressStatus": "In PDD",
    "productionStatus": "Complete",
    "dispatchStatus": "Dispatched",
    "amount": 715238,
    "quantity": "15468 units",
    "status": "Approved",
    "orderDate": "2023-06-25",
    "expectedDelivery": "2023-10-17",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-107",
    "customer": "NTN Bearing",
    "job": "Luxury Gift Boxes",
    "jdoId": "JDO-2024-113",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "prePressStatus": "Complete",
    "productionStatus": "Scheduled",
    "dispatchStatus": "Dispatched",
    "amount": 1063482,
    "quantity": "35776 units",
    "status": "In Review",
    "orderDate": "2023-10-08",
    "expectedDelivery": "2023-11-16",
    "progress": 73,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-108",
    "customer": "Amul",
    "job": "Pharmaceutical Cartons",
    "jdoId": "JDO-2024-098",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "prePressStatus": "Scheduled",
    "productionStatus": "Scheduled",
    "dispatchStatus": "Dispatched",
    "amount": 193601,
    "quantity": "45483 units",
    "status": "Approved",
    "orderDate": "2023-12-12",
    "expectedDelivery": "2024-02-06",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-109",
    "customer": "Pigeon India",
    "job": "Beverage Cartons",
    "jdoId": "JDO-2024-001",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "prePressStatus": "In PDD",
    "productionStatus": "Complete",
    "dispatchStatus": "Scheduled",
    "amount": 1891716,
    "quantity": "32160 units",
    "status": "In Review",
    "orderDate": "2023-11-03",
    "expectedDelivery": "2023-11-27",
    "progress": 66,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-110",
    "customer": "Larsen & Toubro",
    "job": "Snack Packaging",
    "jdoId": "JDO-2024-139",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant A",
    "prePressStatus": "In PDD",
    "productionStatus": "Released",
    "dispatchStatus": "Dispatched",
    "amount": 3998412,
    "quantity": "38482 units",
    "status": "In PDD",
    "orderDate": "2023-07-29",
    "expectedDelivery": "2023-08-20",
    "progress": 52,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-111",
    "customer": "Honeywell India",
    "job": "Electronic Device Boxes",
    "jdoId": "JDO-2024-098",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "prePressStatus": "Scheduled",
    "productionStatus": "Complete",
    "dispatchStatus": "Dispatched",
    "amount": 599308,
    "quantity": "26348 units",
    "status": "In PDD",
    "orderDate": "2023-10-12",
    "expectedDelivery": "2024-01-24",
    "progress": 53,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-112",
    "customer": "Pigeon India",
    "job": "Luxury Gift Boxes",
    "jdoId": "JDO-2024-129",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "prePressStatus": "In PDD",
    "productionStatus": "Approved",
    "dispatchStatus": "Dispatched",
    "amount": 1848572,
    "quantity": "25804 units",
    "status": "In PDD",
    "orderDate": "2023-07-26",
    "expectedDelivery": "2023-08-03",
    "progress": 64,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-113",
    "customer": "TTK Prestige",
    "job": "Tea/Coffee Packaging",
    "jdoId": "JDO-2024-001",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "prePressStatus": "Scheduled",
    "productionStatus": "Approved",
    "dispatchStatus": "Dispatched",
    "amount": 1231008,
    "quantity": "30654 units",
    "status": "In PDD",
    "orderDate": "2023-11-06",
    "expectedDelivery": "2023-11-11",
    "progress": 54,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-114",
    "customer": "Bisleri",
    "job": "Industrial Labels",
    "jdoId": "JDO-2024-041",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "prePressStatus": "Scheduled",
    "productionStatus": "Complete",
    "dispatchStatus": "Dispatched",
    "amount": 2972523,
    "quantity": "5856 units",
    "status": "Approved",
    "orderDate": "2023-07-12",
    "expectedDelivery": "2023-11-01",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-115",
    "customer": "Nike India",
    "job": "Auto Parts Packaging",
    "jdoId": "JDO-2024-143",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "prePressStatus": "Pending",
    "productionStatus": "Released",
    "dispatchStatus": "Dispatched",
    "amount": 3112413,
    "quantity": "33708 units",
    "status": "In Review",
    "orderDate": "2023-11-27",
    "expectedDelivery": "2023-12-23",
    "progress": 69,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-116",
    "customer": "Continental India",
    "job": "Printed Labels",
    "jdoId": "JDO-2024-146",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant A",
    "prePressStatus": "In Progress",
    "productionStatus": "Approved",
    "dispatchStatus": "Pending",
    "amount": 1173813,
    "quantity": "36509 units",
    "status": "In Review",
    "orderDate": "2023-08-18",
    "expectedDelivery": "2024-02-11",
    "progress": 51,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-117",
    "customer": "Cipla Pharmaceuticals",
    "job": "Tea/Coffee Packaging",
    "jdoId": "JDO-2024-046",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "prePressStatus": "Released",
    "productionStatus": "Approved",
    "dispatchStatus": "Dispatched",
    "amount": 4675273,
    "quantity": "26591 units",
    "status": "In PDD",
    "orderDate": "2023-09-22",
    "expectedDelivery": "2024-01-18",
    "progress": 65,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-118",
    "customer": "Pigeon India",
    "job": "Beverage Cartons",
    "jdoId": "JDO-2024-003",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "prePressStatus": "In Progress",
    "productionStatus": "Complete",
    "dispatchStatus": "Scheduled",
    "amount": 420661,
    "quantity": "43956 units",
    "status": "Approved",
    "orderDate": "2024-01-04",
    "expectedDelivery": "2024-02-04",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-119",
    "customer": "Reebok India",
    "job": "Food Grade Packaging",
    "jdoId": "JDO-2024-079",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "prePressStatus": "Pending",
    "productionStatus": "Complete",
    "dispatchStatus": "Pending",
    "amount": 233082,
    "quantity": "10109 units",
    "status": "In Review",
    "orderDate": "2023-08-20",
    "expectedDelivery": "2023-08-20",
    "progress": 81,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-120",
    "customer": "Havells India",
    "job": "Delivery Cartons",
    "jdoId": "JDO-2024-033",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "prePressStatus": "Released",
    "productionStatus": "Released",
    "dispatchStatus": "Pending",
    "amount": 3476839,
    "quantity": "29976 units",
    "status": "In Review",
    "orderDate": "2023-07-06",
    "expectedDelivery": "2024-02-22",
    "progress": 40,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-121",
    "customer": "Cream Bell",
    "job": "Electronic Device Boxes",
    "jdoId": "JDO-2024-047",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "prePressStatus": "Released",
    "productionStatus": "In Progress",
    "dispatchStatus": "Pending",
    "amount": 2755621,
    "quantity": "6575 units",
    "status": "In Review",
    "orderDate": "2023-06-12",
    "expectedDelivery": "2023-06-28",
    "progress": 61,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-122",
    "customer": "Anchor Electricals",
    "job": "Food Grade Packaging",
    "jdoId": "JDO-2024-150",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "prePressStatus": "Scheduled",
    "productionStatus": "In Progress",
    "dispatchStatus": "Pending",
    "amount": 4644060,
    "quantity": "43037 units",
    "status": "In Review",
    "orderDate": "2023-08-03",
    "expectedDelivery": "2024-01-02",
    "progress": 74,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-123",
    "customer": "NTN Bearing",
    "job": "Food Grade Packaging",
    "jdoId": "JDO-2024-145",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "prePressStatus": "Released",
    "productionStatus": "Complete",
    "dispatchStatus": "Dispatched",
    "amount": 1599896,
    "quantity": "8322 units",
    "status": "Approved",
    "orderDate": "2023-11-14",
    "expectedDelivery": "2024-02-17",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-124",
    "customer": "Pidilite Industries",
    "job": "Pharmaceutical Cartons",
    "jdoId": "JDO-2024-105",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "prePressStatus": "Released",
    "productionStatus": "Released",
    "dispatchStatus": "Scheduled",
    "amount": 1709199,
    "quantity": "45104 units",
    "status": "In Review",
    "orderDate": "2023-08-31",
    "expectedDelivery": "2023-12-08",
    "progress": 88,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-125",
    "customer": "Hero MotoCorp",
    "job": "Beverage Cartons",
    "jdoId": "JDO-2024-016",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "prePressStatus": "Scheduled",
    "productionStatus": "Approved",
    "dispatchStatus": "Scheduled",
    "amount": 3818726,
    "quantity": "14230 units",
    "status": "In Review",
    "orderDate": "2023-06-13",
    "expectedDelivery": "2023-09-06",
    "progress": 53,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-126",
    "customer": "Spencer's Retail",
    "job": "Pharmaceutical Cartons",
    "jdoId": "JDO-2024-043",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "prePressStatus": "In PDD",
    "productionStatus": "Complete",
    "dispatchStatus": "Dispatched",
    "amount": 4465093,
    "quantity": "39965 units",
    "status": "Approved",
    "orderDate": "2024-01-05",
    "expectedDelivery": "2024-02-05",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-127",
    "customer": "Samsung India",
    "job": "Snack Packaging",
    "jdoId": "JDO-2024-098",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "prePressStatus": "Approved",
    "productionStatus": "In PDD",
    "dispatchStatus": "Scheduled",
    "amount": 4548178,
    "quantity": "32146 units",
    "status": "Approved",
    "orderDate": "2023-10-10",
    "expectedDelivery": "2024-01-22",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-128",
    "customer": "Bridgestone India",
    "job": "Auto Parts Packaging",
    "jdoId": "JDO-2024-019",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "prePressStatus": "Scheduled",
    "productionStatus": "Pending",
    "dispatchStatus": "Pending",
    "amount": 4198370,
    "quantity": "31637 units",
    "status": "In Review",
    "orderDate": "2023-07-30",
    "expectedDelivery": "2023-10-11",
    "progress": 50,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-129",
    "customer": "Schneider Electric",
    "job": "Corrugated Sheets",
    "jdoId": "JDO-2024-100",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "prePressStatus": "Approved",
    "productionStatus": "Approved",
    "dispatchStatus": "Scheduled",
    "amount": 3418945,
    "quantity": "23234 units",
    "status": "In Review",
    "orderDate": "2023-11-29",
    "expectedDelivery": "2024-01-19",
    "progress": 59,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-130",
    "customer": "Prestige Smart Kitchen",
    "job": "Pharmaceutical Cartons",
    "jdoId": "JDO-2024-106",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "prePressStatus": "Released",
    "productionStatus": "In PDD",
    "dispatchStatus": "Pending",
    "amount": 3196697,
    "quantity": "21340 units",
    "status": "In PDD",
    "orderDate": "2023-08-15",
    "expectedDelivery": "2024-02-20",
    "progress": 61,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-131",
    "customer": "BigBasket",
    "job": "Electronic Device Boxes",
    "jdoId": "JDO-2024-072",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant A",
    "prePressStatus": "Scheduled",
    "productionStatus": "In Progress",
    "dispatchStatus": "Dispatched",
    "amount": 3275504,
    "quantity": "40511 units",
    "status": "In Review",
    "orderDate": "2023-07-28",
    "expectedDelivery": "2023-08-21",
    "progress": 56,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-132",
    "customer": "Bridgestone India",
    "job": "Snack Packaging",
    "jdoId": "JDO-2024-003",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "prePressStatus": "Pending",
    "productionStatus": "In Progress",
    "dispatchStatus": "Dispatched",
    "amount": 1827014,
    "quantity": "2489 units",
    "status": "Approved",
    "orderDate": "2023-09-17",
    "expectedDelivery": "2023-11-03",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-133",
    "customer": "Tata Steel",
    "job": "Delivery Cartons",
    "jdoId": "JDO-2024-063",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "prePressStatus": "Pending",
    "productionStatus": "In PDD",
    "dispatchStatus": "Scheduled",
    "amount": 4127988,
    "quantity": "41322 units",
    "status": "Approved",
    "orderDate": "2023-12-01",
    "expectedDelivery": "2024-01-08",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-134",
    "customer": "Anchor Electricals",
    "job": "Tea/Coffee Packaging",
    "jdoId": "JDO-2024-030",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "prePressStatus": "Approved",
    "productionStatus": "Approved",
    "dispatchStatus": "Dispatched",
    "amount": 4940144,
    "quantity": "9281 units",
    "status": "In Review",
    "orderDate": "2024-01-07",
    "expectedDelivery": "2024-01-22",
    "progress": 61,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-135",
    "customer": "MRF Tyres",
    "job": "Folding Cartons",
    "jdoId": "JDO-2024-102",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "prePressStatus": "Scheduled",
    "productionStatus": "Released",
    "dispatchStatus": "Scheduled",
    "amount": 4264759,
    "quantity": "21194 units",
    "status": "In Review",
    "orderDate": "2023-10-10",
    "expectedDelivery": "2023-10-10",
    "progress": 66,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-136",
    "customer": "Otis Elevator",
    "job": "Auto Parts Packaging",
    "jdoId": "JDO-2024-082",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "prePressStatus": "Approved",
    "productionStatus": "Approved",
    "dispatchStatus": "Scheduled",
    "amount": 2008463,
    "quantity": "47136 units",
    "status": "In Review",
    "orderDate": "2023-09-22",
    "expectedDelivery": "2024-01-03",
    "progress": 47,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-137",
    "customer": "Tech Mahindra",
    "job": "Packaging Boxes",
    "jdoId": "JDO-2024-012",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "prePressStatus": "Released",
    "productionStatus": "Approved",
    "dispatchStatus": "Pending",
    "amount": 3020521,
    "quantity": "25862 units",
    "status": "Approved",
    "orderDate": "2023-08-06",
    "expectedDelivery": "2023-08-07",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-138",
    "customer": "Nike India",
    "job": "Pharmaceutical Cartons",
    "jdoId": "JDO-2024-051",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "prePressStatus": "Pending",
    "productionStatus": "Complete",
    "dispatchStatus": "Dispatched",
    "amount": 3338592,
    "quantity": "42419 units",
    "status": "In Review",
    "orderDate": "2023-06-30",
    "expectedDelivery": "2023-12-21",
    "progress": 91,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-139",
    "customer": "Daikin India",
    "job": "Snack Packaging",
    "jdoId": "JDO-2024-058",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "prePressStatus": "Approved",
    "productionStatus": "In Progress",
    "dispatchStatus": "Dispatched",
    "amount": 3543266,
    "quantity": "31182 units",
    "status": "In Review",
    "orderDate": "2023-10-28",
    "expectedDelivery": "2024-01-29",
    "progress": 68,
    "notes": "In Review - Commercial production ongoing"
  },
  {
    "id": "COM-2024-140",
    "customer": "BigBasket",
    "job": "Food Grade Packaging",
    "jdoId": "JDO-2024-142",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "prePressStatus": "Complete",
    "productionStatus": "Pending",
    "dispatchStatus": "Pending",
    "amount": 1455743,
    "quantity": "30317 units",
    "status": "In PDD",
    "orderDate": "2023-08-04",
    "expectedDelivery": "2024-01-21",
    "progress": 41,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-141",
    "customer": "Reliance Retail",
    "job": "E-commerce Shipping Boxes",
    "jdoId": "JDO-2024-130",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "prePressStatus": "Complete",
    "productionStatus": "In Progress",
    "dispatchStatus": "Scheduled",
    "amount": 868775,
    "quantity": "43347 units",
    "status": "Approved",
    "orderDate": "2023-08-07",
    "expectedDelivery": "2023-10-24",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-142",
    "customer": "Dr Reddy's Labs",
    "job": "Snack Packaging",
    "jdoId": "JDO-2024-150",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "prePressStatus": "Approved",
    "productionStatus": "Approved",
    "dispatchStatus": "Scheduled",
    "amount": 68044,
    "quantity": "24959 units",
    "status": "Approved",
    "orderDate": "2023-08-25",
    "expectedDelivery": "2024-01-19",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-143",
    "customer": "Amul",
    "job": "Delivery Cartons",
    "jdoId": "JDO-2024-033",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "prePressStatus": "Pending",
    "productionStatus": "Complete",
    "dispatchStatus": "Pending",
    "amount": 898242,
    "quantity": "11591 units",
    "status": "Approved",
    "orderDate": "2023-10-29",
    "expectedDelivery": "2023-11-26",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-144",
    "customer": "Dabur India",
    "job": "Industrial Labels",
    "jdoId": "JDO-2024-102",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "prePressStatus": "In PDD",
    "productionStatus": "In PDD",
    "dispatchStatus": "Pending",
    "amount": 3046842,
    "quantity": "24036 units",
    "status": "In PDD",
    "orderDate": "2023-10-14",
    "expectedDelivery": "2023-11-30",
    "progress": 69,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-145",
    "customer": "Sun Pharma",
    "job": "Pharmaceutical Cartons",
    "jdoId": "JDO-2024-037",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "prePressStatus": "Released",
    "productionStatus": "Scheduled",
    "dispatchStatus": "Dispatched",
    "amount": 166009,
    "quantity": "17719 units",
    "status": "Approved",
    "orderDate": "2023-08-21",
    "expectedDelivery": "2023-10-07",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-146",
    "customer": "Flipkart",
    "job": "Die-Cut Boxes",
    "jdoId": "JDO-2024-076",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "prePressStatus": "In PDD",
    "productionStatus": "Scheduled",
    "dispatchStatus": "Scheduled",
    "amount": 3005007,
    "quantity": "41876 units",
    "status": "In PDD",
    "orderDate": "2023-12-11",
    "expectedDelivery": "2024-02-24",
    "progress": 80,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-147",
    "customer": "Decathlon India",
    "job": "Snack Packaging",
    "jdoId": "JDO-2024-081",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant A",
    "prePressStatus": "Complete",
    "productionStatus": "Pending",
    "dispatchStatus": "Dispatched",
    "amount": 3916982,
    "quantity": "35179 units",
    "status": "Approved",
    "orderDate": "2023-11-22",
    "expectedDelivery": "2024-01-24",
    "progress": 100,
    "notes": "Approved - Commercial production completed"
  },
  {
    "id": "COM-2024-148",
    "customer": "Megadyne India",
    "job": "Delivery Cartons",
    "jdoId": "JDO-2024-146",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "prePressStatus": "Complete",
    "productionStatus": "Pending",
    "dispatchStatus": "Scheduled",
    "amount": 2443470,
    "quantity": "11309 units",
    "status": "In PDD",
    "orderDate": "2023-10-30",
    "expectedDelivery": "2024-01-21",
    "progress": 45,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-149",
    "customer": "Blue Star",
    "job": "Industrial Labels",
    "jdoId": "JDO-2024-033",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "prePressStatus": "Released",
    "productionStatus": "Released",
    "dispatchStatus": "Pending",
    "amount": 3349982,
    "quantity": "39692 units",
    "status": "In PDD",
    "orderDate": "2023-12-18",
    "expectedDelivery": "2024-02-07",
    "progress": 57,
    "notes": "In PDD - Commercial production ongoing"
  },
  {
    "id": "COM-2024-150",
    "customer": "Whirlpool India",
    "job": "Electronic Device Boxes",
    "jdoId": "JDO-2024-003",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "prePressStatus": "Pending",
    "productionStatus": "Pending",
    "dispatchStatus": "Scheduled",
    "amount": 1487412,
    "quantity": "39261 units",
    "status": "In PDD",
    "orderDate": "2023-08-02",
    "expectedDelivery": "2024-01-08",
    "progress": 70,
    "notes": "In PDD - Commercial production ongoing"
  }
]
