// Replace const jdoProjects = [...] in projects-content.tsx with this data

export const jdoProjectsData = [
  {
    "id": "JDO-2024-001",
    "customer": "Schneider Electric",
    "job": "Retail Display Boxes",
    "sdoId": "SDO-2024-061",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "artworkStatus": "In Review",
    "bomStatus": "Complete",
    "routingStatus": "Complete",
    "progress": 51,
    "createdDate": "2023-05-19",
    "notes": "In Review artwork, Complete BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-002",
    "customer": "Aditya Birla Group",
    "job": "Delivery Cartons",
    "sdoId": "SDO-2024-028",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "artworkStatus": "Approved",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 77,
    "createdDate": "2023-08-15",
    "notes": "Approved artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-003",
    "customer": "Dabur India",
    "job": "Beverage Cartons",
    "sdoId": "SDO-2024-029",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "artworkStatus": "Clarification",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 75,
    "createdDate": "2023-05-12",
    "notes": "Clarification artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-004",
    "customer": "Reliance Retail",
    "job": "Retail Display Boxes",
    "sdoId": "SDO-2024-036",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "artworkStatus": "Approved",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 84,
    "createdDate": "2023-05-06",
    "notes": "Approved artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-005",
    "customer": "NSK India",
    "job": "Luxury Gift Boxes",
    "sdoId": "SDO-2024-051",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "artworkStatus": "In Review",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 76,
    "createdDate": "2023-10-02",
    "notes": "In Review artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-006",
    "customer": "Nike India",
    "job": "Appliance Cartons",
    "sdoId": "SDO-2024-089",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "artworkStatus": "In Review",
    "bomStatus": "Pending",
    "routingStatus": "Pending",
    "progress": 59,
    "createdDate": "2023-08-21",
    "notes": "In Review artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-007",
    "customer": "Whirlpool India",
    "job": "Cosmetic Packaging",
    "sdoId": "SDO-2024-003",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "artworkStatus": "Clarification",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 47,
    "createdDate": "2023-06-22",
    "notes": "Clarification artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-008",
    "customer": "Kirloskar Electric",
    "job": "Printed Labels",
    "sdoId": "SDO-2024-044",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "artworkStatus": "In Review",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 73,
    "createdDate": "2023-12-25",
    "notes": "In Review artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-009",
    "customer": "Pigeon India",
    "job": "Snack Packaging",
    "sdoId": "SDO-2024-085",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "artworkStatus": "Approved",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 41,
    "createdDate": "2023-05-29",
    "notes": "Approved artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-010",
    "customer": "Red Bull India",
    "job": "E-commerce Shipping Boxes",
    "sdoId": "SDO-2024-036",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "artworkStatus": "In Review",
    "bomStatus": "Complete",
    "routingStatus": "Complete",
    "progress": 71,
    "createdDate": "2023-12-05",
    "notes": "In Review artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-011",
    "customer": "Mother Dairy",
    "job": "Delivery Cartons",
    "sdoId": "SDO-2024-143",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "artworkStatus": "Approved",
    "bomStatus": "Complete",
    "routingStatus": "Clarification",
    "progress": 58,
    "createdDate": "2023-05-24",
    "notes": "Approved artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-012",
    "customer": "Prestige Smart Kitchen",
    "job": "Industrial Labels",
    "sdoId": "SDO-2024-027",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "artworkStatus": "Pending",
    "bomStatus": "Pending",
    "routingStatus": "Pending",
    "progress": 81,
    "createdDate": "2023-05-25",
    "notes": "Pending artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-013",
    "customer": "Milton India",
    "job": "Luxury Gift Boxes",
    "sdoId": "SDO-2024-010",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "artworkStatus": "Clarification",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 31,
    "createdDate": "2023-09-17",
    "notes": "Clarification artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-014",
    "customer": "Nike India",
    "job": "Medicine Cartons",
    "sdoId": "SDO-2024-024",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "artworkStatus": "In Review",
    "bomStatus": "Complete",
    "routingStatus": "Clarification",
    "progress": 52,
    "createdDate": "2023-11-08",
    "notes": "In Review artwork, Complete BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-015",
    "customer": "Tata Steel",
    "job": "Luxury Gift Boxes",
    "sdoId": "SDO-2024-040",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "artworkStatus": "Pending",
    "bomStatus": "Clarification",
    "routingStatus": "Pending",
    "progress": 34,
    "createdDate": "2023-05-10",
    "notes": "Pending artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-016",
    "customer": "Decathlon India",
    "job": "Industrial Labels",
    "sdoId": "SDO-2024-037",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "artworkStatus": "Approved",
    "bomStatus": "Clarification",
    "routingStatus": "Pending",
    "progress": 49,
    "createdDate": "2023-06-12",
    "notes": "Approved artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-017",
    "customer": "Tropicana India",
    "job": "Electronic Device Boxes",
    "sdoId": "SDO-2024-041",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "artworkStatus": "In Review",
    "bomStatus": "Pending",
    "routingStatus": "Pending",
    "progress": 52,
    "createdDate": "2023-10-15",
    "notes": "In Review artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-018",
    "customer": "Red Bull India",
    "job": "Auto Parts Packaging",
    "sdoId": "SDO-2024-001",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "artworkStatus": "Approved",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 49,
    "createdDate": "2023-07-27",
    "notes": "Approved artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-019",
    "customer": "LG Electronics",
    "job": "Auto Parts Packaging",
    "sdoId": "SDO-2024-112",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "artworkStatus": "In Review",
    "bomStatus": "Pending",
    "routingStatus": "Clarification",
    "progress": 41,
    "createdDate": "2023-08-24",
    "notes": "In Review artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-020",
    "customer": "Carrier Midea India",
    "job": "Printed Labels",
    "sdoId": "SDO-2024-001",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "artworkStatus": "In Review",
    "bomStatus": "Clarification",
    "routingStatus": "Pending",
    "progress": 48,
    "createdDate": "2023-06-22",
    "notes": "In Review artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-021",
    "customer": "TVS Motor",
    "job": "Folding Cartons",
    "sdoId": "SDO-2024-084",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "artworkStatus": "In Review",
    "bomStatus": "Complete",
    "routingStatus": "Clarification",
    "progress": 35,
    "createdDate": "2023-06-07",
    "notes": "In Review artwork, Complete BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-022",
    "customer": "Hindustan Unilever",
    "job": "Snack Packaging",
    "sdoId": "SDO-2024-068",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "artworkStatus": "In Review",
    "bomStatus": "Pending",
    "routingStatus": "Clarification",
    "progress": 86,
    "createdDate": "2023-07-17",
    "notes": "In Review artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-023",
    "customer": "Cream Bell",
    "job": "Printed Labels",
    "sdoId": "SDO-2024-052",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant A",
    "artworkStatus": "Clarification",
    "bomStatus": "Complete",
    "routingStatus": "Clarification",
    "progress": 39,
    "createdDate": "2023-08-04",
    "notes": "Clarification artwork, Complete BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-024",
    "customer": "Dr Reddy's Labs",
    "job": "Pharmaceutical Cartons",
    "sdoId": "SDO-2024-028",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "artworkStatus": "Approved",
    "bomStatus": "Pending",
    "routingStatus": "Pending",
    "progress": 87,
    "createdDate": "2024-01-13",
    "notes": "Approved artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-025",
    "customer": "Godrej Industries",
    "job": "Appliance Cartons",
    "sdoId": "SDO-2024-072",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "artworkStatus": "In Review",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 66,
    "createdDate": "2023-09-06",
    "notes": "In Review artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-026",
    "customer": "Voltas Limited",
    "job": "Appliance Cartons",
    "sdoId": "SDO-2024-126",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "artworkStatus": "Pending",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 89,
    "createdDate": "2023-12-03",
    "notes": "Pending artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-027",
    "customer": "Adidas India",
    "job": "Corrugated Sheets",
    "sdoId": "SDO-2024-050",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "artworkStatus": "Pending",
    "bomStatus": "Complete",
    "routingStatus": "Clarification",
    "progress": 30,
    "createdDate": "2023-05-24",
    "notes": "Pending artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-028",
    "customer": "Hitachi India",
    "job": "Beverage Cartons",
    "sdoId": "SDO-2024-014",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "artworkStatus": "In Review",
    "bomStatus": "Clarification",
    "routingStatus": "Pending",
    "progress": 81,
    "createdDate": "2023-07-16",
    "notes": "In Review artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-029",
    "customer": "Cummins India",
    "job": "Electronic Device Boxes",
    "sdoId": "SDO-2024-051",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "artworkStatus": "Clarification",
    "bomStatus": "Complete",
    "routingStatus": "Complete",
    "progress": 59,
    "createdDate": "2023-07-07",
    "notes": "Clarification artwork, Complete BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-030",
    "customer": "Continental India",
    "job": "Corrugated Sheets",
    "sdoId": "SDO-2024-067",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "artworkStatus": "Approved",
    "bomStatus": "Pending",
    "routingStatus": "Pending",
    "progress": 82,
    "createdDate": "2023-07-31",
    "notes": "Approved artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-031",
    "customer": "Daikin India",
    "job": "Printed Labels",
    "sdoId": "SDO-2024-024",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "artworkStatus": "In Review",
    "bomStatus": "Complete",
    "routingStatus": "Pending",
    "progress": 70,
    "createdDate": "2023-08-18",
    "notes": "In Review artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-032",
    "customer": "Tech Mahindra",
    "job": "Retail Display Boxes",
    "sdoId": "SDO-2024-064",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "artworkStatus": "Clarification",
    "bomStatus": "Clarification",
    "routingStatus": "Complete",
    "progress": 64,
    "createdDate": "2023-08-02",
    "notes": "Clarification artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-033",
    "customer": "Reliance Retail",
    "job": "Food Grade Packaging",
    "sdoId": "SDO-2024-059",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "artworkStatus": "Approved",
    "bomStatus": "Pending",
    "routingStatus": "Pending",
    "progress": 81,
    "createdDate": "2023-12-31",
    "notes": "Approved artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-034",
    "customer": "BHEL India",
    "job": "Electronic Device Boxes",
    "sdoId": "SDO-2024-073",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "artworkStatus": "In Review",
    "bomStatus": "Pending",
    "routingStatus": "Clarification",
    "progress": 53,
    "createdDate": "2023-07-08",
    "notes": "In Review artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-035",
    "customer": "Prestige Smart Kitchen",
    "job": "Packaging Boxes",
    "sdoId": "SDO-2024-053",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "artworkStatus": "In Review",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 74,
    "createdDate": "2023-05-10",
    "notes": "In Review artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-036",
    "customer": "Asian Paints Ltd",
    "job": "Appliance Cartons",
    "sdoId": "SDO-2024-076",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "artworkStatus": "Approved",
    "bomStatus": "Complete",
    "routingStatus": "Clarification",
    "progress": 43,
    "createdDate": "2023-06-03",
    "notes": "Approved artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-037",
    "customer": "Red Bull India",
    "job": "Shipping Containers",
    "sdoId": "SDO-2024-075",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "artworkStatus": "Pending",
    "bomStatus": "Clarification",
    "routingStatus": "Pending",
    "progress": 48,
    "createdDate": "2023-08-08",
    "notes": "Pending artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-038",
    "customer": "Decathlon India",
    "job": "Pharmaceutical Cartons",
    "sdoId": "SDO-2024-084",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "artworkStatus": "Approved",
    "bomStatus": "Pending",
    "routingStatus": "Clarification",
    "progress": 46,
    "createdDate": "2023-09-05",
    "notes": "Approved artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-039",
    "customer": "JK Tyre",
    "job": "Tea/Coffee Packaging",
    "sdoId": "SDO-2024-091",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "artworkStatus": "Pending",
    "bomStatus": "Pending",
    "routingStatus": "Clarification",
    "progress": 60,
    "createdDate": "2023-06-01",
    "notes": "Pending artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-040",
    "customer": "Adidas India",
    "job": "Folding Cartons",
    "sdoId": "SDO-2024-114",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "artworkStatus": "Approved",
    "bomStatus": "Complete",
    "routingStatus": "Clarification",
    "progress": 53,
    "createdDate": "2023-07-08",
    "notes": "Approved artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-041",
    "customer": "Crompton Greaves",
    "job": "Packaging Boxes",
    "sdoId": "SDO-2024-027",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "artworkStatus": "In Review",
    "bomStatus": "Complete",
    "routingStatus": "Pending",
    "progress": 30,
    "createdDate": "2023-10-11",
    "notes": "In Review artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-042",
    "customer": "Puma India",
    "job": "Auto Parts Packaging",
    "sdoId": "SDO-2024-138",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "artworkStatus": "Approved",
    "bomStatus": "Complete",
    "routingStatus": "Pending",
    "progress": 66,
    "createdDate": "2023-09-19",
    "notes": "Approved artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-043",
    "customer": "Nike India",
    "job": "Delivery Cartons",
    "sdoId": "SDO-2024-143",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "artworkStatus": "Approved",
    "bomStatus": "Complete",
    "routingStatus": "Clarification",
    "progress": 30,
    "createdDate": "2023-09-08",
    "notes": "Approved artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-044",
    "customer": "LG Electronics",
    "job": "Packaging Boxes",
    "sdoId": "SDO-2024-017",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "artworkStatus": "Clarification",
    "bomStatus": "Complete",
    "routingStatus": "Complete",
    "progress": 46,
    "createdDate": "2023-06-22",
    "notes": "Clarification artwork, Complete BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-045",
    "customer": "Carrier Midea India",
    "job": "Folding Cartons",
    "sdoId": "SDO-2024-123",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "artworkStatus": "In Review",
    "bomStatus": "Clarification",
    "routingStatus": "Pending",
    "progress": 45,
    "createdDate": "2023-09-27",
    "notes": "In Review artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-046",
    "customer": "Red Bull India",
    "job": "Folding Cartons",
    "sdoId": "SDO-2024-096",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "artworkStatus": "Clarification",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 50,
    "createdDate": "2024-01-08",
    "notes": "Clarification artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-047",
    "customer": "Tata Steel",
    "job": "Corrugated Sheets",
    "sdoId": "SDO-2024-127",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "artworkStatus": "Pending",
    "bomStatus": "Pending",
    "routingStatus": "Clarification",
    "progress": 61,
    "createdDate": "2023-10-31",
    "notes": "Pending artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-048",
    "customer": "Blue Star",
    "job": "Tea/Coffee Packaging",
    "sdoId": "SDO-2024-015",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "artworkStatus": "Pending",
    "bomStatus": "Complete",
    "routingStatus": "Pending",
    "progress": 89,
    "createdDate": "2023-12-29",
    "notes": "Pending artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-049",
    "customer": "BHEL India",
    "job": "Folding Cartons",
    "sdoId": "SDO-2024-041",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "artworkStatus": "In Review",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 62,
    "createdDate": "2023-12-28",
    "notes": "In Review artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-050",
    "customer": "Swiggy",
    "job": "Pharmaceutical Cartons",
    "sdoId": "SDO-2024-113",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "artworkStatus": "Pending",
    "bomStatus": "Pending",
    "routingStatus": "Pending",
    "progress": 89,
    "createdDate": "2023-05-21",
    "notes": "Pending artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-051",
    "customer": "Zomato",
    "job": "Appliance Cartons",
    "sdoId": "SDO-2024-040",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "artworkStatus": "Clarification",
    "bomStatus": "Complete",
    "routingStatus": "Pending",
    "progress": 64,
    "createdDate": "2023-08-15",
    "notes": "Clarification artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-052",
    "customer": "Cipla Pharmaceuticals",
    "job": "Printed Labels",
    "sdoId": "SDO-2024-133",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "artworkStatus": "Approved",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 40,
    "createdDate": "2023-09-16",
    "notes": "Approved artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-053",
    "customer": "DMart",
    "job": "Appliance Cartons",
    "sdoId": "SDO-2024-052",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "artworkStatus": "Approved",
    "bomStatus": "Pending",
    "routingStatus": "Clarification",
    "progress": 88,
    "createdDate": "2023-08-04",
    "notes": "Approved artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-054",
    "customer": "Havells India",
    "job": "Electronic Device Boxes",
    "sdoId": "SDO-2024-034",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "artworkStatus": "Pending",
    "bomStatus": "Pending",
    "routingStatus": "Clarification",
    "progress": 79,
    "createdDate": "2023-08-02",
    "notes": "Pending artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-055",
    "customer": "TTK Prestige",
    "job": "Folding Cartons",
    "sdoId": "SDO-2024-002",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "artworkStatus": "Clarification",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 54,
    "createdDate": "2023-11-19",
    "notes": "Clarification artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-056",
    "customer": "Godrej Industries",
    "job": "Beverage Cartons",
    "sdoId": "SDO-2024-013",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "artworkStatus": "Clarification",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 77,
    "createdDate": "2023-11-22",
    "notes": "Clarification artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-057",
    "customer": "Optibelt India",
    "job": "Retail Display Boxes",
    "sdoId": "SDO-2024-137",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "artworkStatus": "In Review",
    "bomStatus": "Clarification",
    "routingStatus": "Complete",
    "progress": 35,
    "createdDate": "2023-06-23",
    "notes": "In Review artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-058",
    "customer": "Nestle India",
    "job": "Beverage Cartons",
    "sdoId": "SDO-2024-104",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "artworkStatus": "In Review",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 67,
    "createdDate": "2023-11-27",
    "notes": "In Review artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-059",
    "customer": "Milton India",
    "job": "Delivery Cartons",
    "sdoId": "SDO-2024-056",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "artworkStatus": "Approved",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 62,
    "createdDate": "2023-11-02",
    "notes": "Approved artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-060",
    "customer": "ITC Limited",
    "job": "Pharmaceutical Cartons",
    "sdoId": "SDO-2024-138",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "artworkStatus": "Pending",
    "bomStatus": "Clarification",
    "routingStatus": "Pending",
    "progress": 58,
    "createdDate": "2023-08-07",
    "notes": "Pending artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-061",
    "customer": "Ceat Tyres",
    "job": "Auto Parts Packaging",
    "sdoId": "SDO-2024-110",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "artworkStatus": "Approved",
    "bomStatus": "Complete",
    "routingStatus": "Complete",
    "progress": 100,
    "createdDate": "2023-10-31",
    "notes": "Ready for commercial PO",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-062",
    "customer": "Bisleri",
    "job": "Beverage Cartons",
    "sdoId": "SDO-2024-108",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "artworkStatus": "Pending",
    "bomStatus": "Complete",
    "routingStatus": "Clarification",
    "progress": 85,
    "createdDate": "2023-08-05",
    "notes": "Pending artwork, Complete BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-063",
    "customer": "Coca-Cola India",
    "job": "Tea/Coffee Packaging",
    "sdoId": "SDO-2024-014",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "artworkStatus": "Clarification",
    "bomStatus": "Complete",
    "routingStatus": "Complete",
    "progress": 54,
    "createdDate": "2023-11-16",
    "notes": "Clarification artwork, Complete BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-064",
    "customer": "Patanjali Ayurved",
    "job": "Beverage Cartons",
    "sdoId": "SDO-2024-129",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "artworkStatus": "Pending",
    "bomStatus": "Pending",
    "routingStatus": "Pending",
    "progress": 58,
    "createdDate": "2024-01-06",
    "notes": "Pending artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-065",
    "customer": "Samsung India",
    "job": "Corrugated Sheets",
    "sdoId": "SDO-2024-052",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "artworkStatus": "In Review",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 85,
    "createdDate": "2023-07-31",
    "notes": "In Review artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-066",
    "customer": "Vedanta Limited",
    "job": "Corrugated Sheets",
    "sdoId": "SDO-2024-130",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "artworkStatus": "Approved",
    "bomStatus": "Clarification",
    "routingStatus": "Complete",
    "progress": 58,
    "createdDate": "2023-05-19",
    "notes": "Approved artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-067",
    "customer": "DMart",
    "job": "E-commerce Shipping Boxes",
    "sdoId": "SDO-2024-102",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "artworkStatus": "Approved",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 71,
    "createdDate": "2023-07-09",
    "notes": "Approved artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-068",
    "customer": "BHEL India",
    "job": "Electronic Device Boxes",
    "sdoId": "SDO-2024-044",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "artworkStatus": "Clarification",
    "bomStatus": "Pending",
    "routingStatus": "Clarification",
    "progress": 65,
    "createdDate": "2023-08-17",
    "notes": "Clarification artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-069",
    "customer": "Mother Dairy",
    "job": "Beverage Cartons",
    "sdoId": "SDO-2024-101",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "artworkStatus": "In Review",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 51,
    "createdDate": "2023-11-15",
    "notes": "In Review artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-070",
    "customer": "V-Guard Industries",
    "job": "Retail Display Boxes",
    "sdoId": "SDO-2024-078",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "artworkStatus": "Approved",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 32,
    "createdDate": "2023-07-21",
    "notes": "Approved artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-071",
    "customer": "GE India",
    "job": "E-commerce Shipping Boxes",
    "sdoId": "SDO-2024-058",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "artworkStatus": "In Review",
    "bomStatus": "Complete",
    "routingStatus": "Pending",
    "progress": 55,
    "createdDate": "2023-08-27",
    "notes": "In Review artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-072",
    "customer": "Zomato",
    "job": "Cosmetic Packaging",
    "sdoId": "SDO-2024-080",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "artworkStatus": "Pending",
    "bomStatus": "Pending",
    "routingStatus": "Pending",
    "progress": 67,
    "createdDate": "2023-07-22",
    "notes": "Pending artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-073",
    "customer": "Godrej Industries",
    "job": "Pharmaceutical Cartons",
    "sdoId": "SDO-2024-052",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "artworkStatus": "Approved",
    "bomStatus": "Clarification",
    "routingStatus": "Complete",
    "progress": 34,
    "createdDate": "2023-09-05",
    "notes": "Approved artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-074",
    "customer": "Legrand India",
    "job": "Die-Cut Boxes",
    "sdoId": "SDO-2024-074",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "artworkStatus": "Clarification",
    "bomStatus": "Clarification",
    "routingStatus": "Pending",
    "progress": 38,
    "createdDate": "2023-10-19",
    "notes": "Clarification artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-075",
    "customer": "Amazon India",
    "job": "Luxury Gift Boxes",
    "sdoId": "SDO-2024-027",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "artworkStatus": "Approved",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 70,
    "createdDate": "2023-05-12",
    "notes": "Approved artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-076",
    "customer": "Fenner India",
    "job": "Appliance Cartons",
    "sdoId": "SDO-2024-017",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "artworkStatus": "Clarification",
    "bomStatus": "Clarification",
    "routingStatus": "Pending",
    "progress": 58,
    "createdDate": "2023-12-10",
    "notes": "Clarification artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-077",
    "customer": "Future Retail",
    "job": "Retail Display Boxes",
    "sdoId": "SDO-2024-064",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant A",
    "artworkStatus": "Approved",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 83,
    "createdDate": "2023-06-14",
    "notes": "Approved artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-078",
    "customer": "Fenner India",
    "job": "Shipping Containers",
    "sdoId": "SDO-2024-116",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "artworkStatus": "Approved",
    "bomStatus": "Pending",
    "routingStatus": "Pending",
    "progress": 41,
    "createdDate": "2023-11-09",
    "notes": "Approved artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-079",
    "customer": "Puma India",
    "job": "Die-Cut Boxes",
    "sdoId": "SDO-2024-054",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "artworkStatus": "Pending",
    "bomStatus": "Complete",
    "routingStatus": "Clarification",
    "progress": 52,
    "createdDate": "2023-06-27",
    "notes": "Pending artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-080",
    "customer": "Tech Mahindra",
    "job": "Die-Cut Boxes",
    "sdoId": "SDO-2024-031",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "artworkStatus": "Clarification",
    "bomStatus": "Complete",
    "routingStatus": "Pending",
    "progress": 32,
    "createdDate": "2023-12-31",
    "notes": "Clarification artwork, Complete BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-081",
    "customer": "Bosch India",
    "job": "Auto Parts Packaging",
    "sdoId": "SDO-2024-138",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant A",
    "artworkStatus": "Approved",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 31,
    "createdDate": "2023-10-03",
    "notes": "Approved artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-082",
    "customer": "Milton India",
    "job": "Shipping Containers",
    "sdoId": "SDO-2024-085",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "artworkStatus": "Pending",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 68,
    "createdDate": "2023-07-05",
    "notes": "Pending artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-083",
    "customer": "Whirlpool India",
    "job": "Pharmaceutical Cartons",
    "sdoId": "SDO-2024-078",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "artworkStatus": "Approved",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 65,
    "createdDate": "2023-12-01",
    "notes": "Approved artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-084",
    "customer": "BHEL India",
    "job": "Retail Display Boxes",
    "sdoId": "SDO-2024-032",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "artworkStatus": "In Review",
    "bomStatus": "Complete",
    "routingStatus": "Complete",
    "progress": 46,
    "createdDate": "2023-07-31",
    "notes": "In Review artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-085",
    "customer": "JK Tyre",
    "job": "Beverage Cartons",
    "sdoId": "SDO-2024-073",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "artworkStatus": "In Review",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 45,
    "createdDate": "2023-10-03",
    "notes": "In Review artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-086",
    "customer": "Gates India",
    "job": "Medicine Cartons",
    "sdoId": "SDO-2024-058",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "artworkStatus": "Pending",
    "bomStatus": "Clarification",
    "routingStatus": "Complete",
    "progress": 56,
    "createdDate": "2023-08-06",
    "notes": "Pending artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-087",
    "customer": "Swiggy",
    "job": "Medicine Cartons",
    "sdoId": "SDO-2024-027",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "artworkStatus": "Clarification",
    "bomStatus": "Pending",
    "routingStatus": "Clarification",
    "progress": 52,
    "createdDate": "2023-09-12",
    "notes": "Clarification artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-088",
    "customer": "Amul",
    "job": "Pharmaceutical Cartons",
    "sdoId": "SDO-2024-119",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "artworkStatus": "Clarification",
    "bomStatus": "Clarification",
    "routingStatus": "Pending",
    "progress": 85,
    "createdDate": "2023-11-14",
    "notes": "Clarification artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-089",
    "customer": "Bajaj Auto",
    "job": "Shipping Containers",
    "sdoId": "SDO-2024-058",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "artworkStatus": "In Review",
    "bomStatus": "Pending",
    "routingStatus": "Clarification",
    "progress": 61,
    "createdDate": "2024-01-07",
    "notes": "In Review artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-090",
    "customer": "GE India",
    "job": "Luxury Gift Boxes",
    "sdoId": "SDO-2024-051",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "artworkStatus": "In Review",
    "bomStatus": "Complete",
    "routingStatus": "Clarification",
    "progress": 77,
    "createdDate": "2023-05-18",
    "notes": "In Review artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-091",
    "customer": "Daikin India",
    "job": "Pharmaceutical Cartons",
    "sdoId": "SDO-2024-095",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "artworkStatus": "In Review",
    "bomStatus": "Clarification",
    "routingStatus": "Complete",
    "progress": 58,
    "createdDate": "2023-05-15",
    "notes": "In Review artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-092",
    "customer": "MRF Tyres",
    "job": "Packaging Boxes",
    "sdoId": "SDO-2024-059",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "artworkStatus": "In Review",
    "bomStatus": "Pending",
    "routingStatus": "Clarification",
    "progress": 56,
    "createdDate": "2023-06-20",
    "notes": "In Review artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-093",
    "customer": "Siemens India",
    "job": "Printed Labels",
    "sdoId": "SDO-2024-039",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "artworkStatus": "In Review",
    "bomStatus": "Complete",
    "routingStatus": "Clarification",
    "progress": 66,
    "createdDate": "2023-08-22",
    "notes": "In Review artwork, Complete BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-094",
    "customer": "Patanjali Ayurved",
    "job": "Industrial Labels",
    "sdoId": "SDO-2024-140",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "artworkStatus": "Pending",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 70,
    "createdDate": "2023-10-22",
    "notes": "Pending artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-095",
    "customer": "JSW Steel",
    "job": "Medicine Cartons",
    "sdoId": "SDO-2024-075",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "artworkStatus": "In Review",
    "bomStatus": "Complete",
    "routingStatus": "Pending",
    "progress": 89,
    "createdDate": "2023-06-30",
    "notes": "In Review artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-096",
    "customer": "ABB India",
    "job": "Snack Packaging",
    "sdoId": "SDO-2024-146",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "artworkStatus": "Approved",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 59,
    "createdDate": "2023-11-29",
    "notes": "Approved artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-097",
    "customer": "Tata Steel",
    "job": "Cosmetic Packaging",
    "sdoId": "SDO-2024-099",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "artworkStatus": "Clarification",
    "bomStatus": "Pending",
    "routingStatus": "Pending",
    "progress": 83,
    "createdDate": "2023-10-18",
    "notes": "Clarification artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-098",
    "customer": "Crompton Greaves",
    "job": "Cosmetic Packaging",
    "sdoId": "SDO-2024-140",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "artworkStatus": "Pending",
    "bomStatus": "Pending",
    "routingStatus": "Clarification",
    "progress": 83,
    "createdDate": "2023-07-10",
    "notes": "Pending artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-099",
    "customer": "NTN Bearing",
    "job": "Folding Cartons",
    "sdoId": "SDO-2024-071",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant A",
    "artworkStatus": "Approved",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 86,
    "createdDate": "2023-05-31",
    "notes": "Approved artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-100",
    "customer": "Cipla Pharmaceuticals",
    "job": "Snack Packaging",
    "sdoId": "SDO-2024-015",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "artworkStatus": "Approved",
    "bomStatus": "Complete",
    "routingStatus": "Pending",
    "progress": 36,
    "createdDate": "2023-10-03",
    "notes": "Approved artwork, Complete BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-101",
    "customer": "ThyssenKrupp Elevators",
    "job": "Folding Cartons",
    "sdoId": "SDO-2024-027",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "artworkStatus": "In Review",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 67,
    "createdDate": "2023-06-27",
    "notes": "In Review artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-102",
    "customer": "Schneider Electric",
    "job": "Appliance Cartons",
    "sdoId": "SDO-2024-011",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "artworkStatus": "Approved",
    "bomStatus": "Clarification",
    "routingStatus": "Complete",
    "progress": 44,
    "createdDate": "2023-12-29",
    "notes": "Approved artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-103",
    "customer": "Hero MotoCorp",
    "job": "Food Grade Packaging",
    "sdoId": "SDO-2024-124",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "artworkStatus": "Pending",
    "bomStatus": "Complete",
    "routingStatus": "Clarification",
    "progress": 55,
    "createdDate": "2023-07-31",
    "notes": "Pending artwork, Complete BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-104",
    "customer": "Schneider Electric",
    "job": "Snack Packaging",
    "sdoId": "SDO-2024-074",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "artworkStatus": "Approved",
    "bomStatus": "Clarification",
    "routingStatus": "Complete",
    "progress": 78,
    "createdDate": "2023-08-03",
    "notes": "Approved artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-105",
    "customer": "NTN Bearing",
    "job": "Auto Parts Packaging",
    "sdoId": "SDO-2024-071",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "artworkStatus": "In Review",
    "bomStatus": "Clarification",
    "routingStatus": "Complete",
    "progress": 68,
    "createdDate": "2023-12-26",
    "notes": "In Review artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-106",
    "customer": "Reebok India",
    "job": "Appliance Cartons",
    "sdoId": "SDO-2024-027",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "artworkStatus": "Pending",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 57,
    "createdDate": "2024-01-07",
    "notes": "Pending artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-107",
    "customer": "Megadyne India",
    "job": "Auto Parts Packaging",
    "sdoId": "SDO-2024-025",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "artworkStatus": "Pending",
    "bomStatus": "Pending",
    "routingStatus": "Pending",
    "progress": 30,
    "createdDate": "2023-09-10",
    "notes": "Pending artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-108",
    "customer": "Schneider Electric",
    "job": "Retail Display Boxes",
    "sdoId": "SDO-2024-077",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "artworkStatus": "Approved",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 45,
    "createdDate": "2023-08-20",
    "notes": "Approved artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-109",
    "customer": "Myntra Fashion",
    "job": "Food Grade Packaging",
    "sdoId": "SDO-2024-111",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "artworkStatus": "Pending",
    "bomStatus": "Complete",
    "routingStatus": "Pending",
    "progress": 85,
    "createdDate": "2023-10-16",
    "notes": "Pending artwork, Complete BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-110",
    "customer": "Nestle India",
    "job": "Luxury Gift Boxes",
    "sdoId": "SDO-2024-069",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "artworkStatus": "Pending",
    "bomStatus": "Complete",
    "routingStatus": "Pending",
    "progress": 67,
    "createdDate": "2023-08-03",
    "notes": "Pending artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-111",
    "customer": "Kwality Walls",
    "job": "Industrial Labels",
    "sdoId": "SDO-2024-002",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "artworkStatus": "In Review",
    "bomStatus": "Complete",
    "routingStatus": "Pending",
    "progress": 81,
    "createdDate": "2024-01-13",
    "notes": "In Review artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-112",
    "customer": "JK Tyre",
    "job": "Packaging Boxes",
    "sdoId": "SDO-2024-056",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "artworkStatus": "Pending",
    "bomStatus": "Clarification",
    "routingStatus": "Pending",
    "progress": 34,
    "createdDate": "2024-01-04",
    "notes": "Pending artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-113",
    "customer": "Bosch India",
    "job": "Beverage Cartons",
    "sdoId": "SDO-2024-084",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "artworkStatus": "In Review",
    "bomStatus": "Complete",
    "routingStatus": "Clarification",
    "progress": 39,
    "createdDate": "2023-07-07",
    "notes": "In Review artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-114",
    "customer": "Spencer's Retail",
    "job": "Auto Parts Packaging",
    "sdoId": "SDO-2024-061",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "artworkStatus": "Clarification",
    "bomStatus": "Clarification",
    "routingStatus": "Complete",
    "progress": 59,
    "createdDate": "2024-01-09",
    "notes": "Clarification artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-115",
    "customer": "Spencer's Retail",
    "job": "Folding Cartons",
    "sdoId": "SDO-2024-041",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "artworkStatus": "Clarification",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 87,
    "createdDate": "2023-09-01",
    "notes": "Clarification artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-116",
    "customer": "Hero MotoCorp",
    "job": "Auto Parts Packaging",
    "sdoId": "SDO-2024-038",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "artworkStatus": "Approved",
    "bomStatus": "Complete",
    "routingStatus": "Complete",
    "progress": 100,
    "createdDate": "2023-12-06",
    "notes": "Ready for commercial PO",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-117",
    "customer": "Mother Dairy",
    "job": "Cosmetic Packaging",
    "sdoId": "SDO-2024-122",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "artworkStatus": "Pending",
    "bomStatus": "Complete",
    "routingStatus": "Clarification",
    "progress": 79,
    "createdDate": "2023-10-06",
    "notes": "Pending artwork, Complete BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-118",
    "customer": "Aditya Birla Group",
    "job": "Food Grade Packaging",
    "sdoId": "SDO-2024-110",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "artworkStatus": "Clarification",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 39,
    "createdDate": "2023-07-05",
    "notes": "Clarification artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-119",
    "customer": "Reebok India",
    "job": "Medicine Cartons",
    "sdoId": "SDO-2024-042",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "artworkStatus": "Approved",
    "bomStatus": "Pending",
    "routingStatus": "Clarification",
    "progress": 46,
    "createdDate": "2023-12-02",
    "notes": "Approved artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-120",
    "customer": "Bosch India",
    "job": "Pharmaceutical Cartons",
    "sdoId": "SDO-2024-071",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant A",
    "artworkStatus": "Pending",
    "bomStatus": "Complete",
    "routingStatus": "Pending",
    "progress": 83,
    "createdDate": "2023-06-15",
    "notes": "Pending artwork, Complete BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-121",
    "customer": "Daikin India",
    "job": "Appliance Cartons",
    "sdoId": "SDO-2024-101",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "artworkStatus": "Approved",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 49,
    "createdDate": "2023-11-16",
    "notes": "Approved artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-122",
    "customer": "Puma India",
    "job": "Retail Display Boxes",
    "sdoId": "SDO-2024-039",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "artworkStatus": "Approved",
    "bomStatus": "Clarification",
    "routingStatus": "Pending",
    "progress": 67,
    "createdDate": "2023-09-02",
    "notes": "Approved artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-123",
    "customer": "Maruti Suzuki",
    "job": "Electronic Device Boxes",
    "sdoId": "SDO-2024-126",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant A",
    "artworkStatus": "Approved",
    "bomStatus": "Complete",
    "routingStatus": "Complete",
    "progress": 100,
    "createdDate": "2023-09-06",
    "notes": "Ready for commercial PO",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-124",
    "customer": "Myntra Fashion",
    "job": "Auto Parts Packaging",
    "sdoId": "SDO-2024-022",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant A",
    "artworkStatus": "Pending",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 48,
    "createdDate": "2023-12-09",
    "notes": "Pending artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-125",
    "customer": "Timken India",
    "job": "Printed Labels",
    "sdoId": "SDO-2024-123",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "artworkStatus": "In Review",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 84,
    "createdDate": "2024-01-05",
    "notes": "In Review artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-126",
    "customer": "Mother Dairy",
    "job": "Cosmetic Packaging",
    "sdoId": "SDO-2024-097",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant B",
    "artworkStatus": "Pending",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 75,
    "createdDate": "2023-10-17",
    "notes": "Pending artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-127",
    "customer": "Nestle India",
    "job": "Medicine Cartons",
    "sdoId": "SDO-2024-108",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "artworkStatus": "In Review",
    "bomStatus": "Complete",
    "routingStatus": "Clarification",
    "progress": 32,
    "createdDate": "2023-08-13",
    "notes": "In Review artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-128",
    "customer": "Sony India",
    "job": "Auto Parts Packaging",
    "sdoId": "SDO-2024-122",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "artworkStatus": "Clarification",
    "bomStatus": "Complete",
    "routingStatus": "Clarification",
    "progress": 36,
    "createdDate": "2023-09-10",
    "notes": "Clarification artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-129",
    "customer": "Britannia Industries",
    "job": "Snack Packaging",
    "sdoId": "SDO-2024-140",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "artworkStatus": "Pending",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 66,
    "createdDate": "2023-08-13",
    "notes": "Pending artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-130",
    "customer": "DMart",
    "job": "Printed Labels",
    "sdoId": "SDO-2024-141",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "artworkStatus": "Clarification",
    "bomStatus": "Pending",
    "routingStatus": "Clarification",
    "progress": 69,
    "createdDate": "2023-12-22",
    "notes": "Clarification artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-131",
    "customer": "MRF Tyres",
    "job": "Industrial Labels",
    "sdoId": "SDO-2024-106",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant D",
    "artworkStatus": "Pending",
    "bomStatus": "Clarification",
    "routingStatus": "Pending",
    "progress": 82,
    "createdDate": "2024-01-01",
    "notes": "Pending artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-132",
    "customer": "Tata Motors",
    "job": "Auto Parts Packaging",
    "sdoId": "SDO-2024-033",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "artworkStatus": "In Review",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 61,
    "createdDate": "2023-11-19",
    "notes": "In Review artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-133",
    "customer": "Zomato",
    "job": "Beverage Cartons",
    "sdoId": "SDO-2024-034",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "artworkStatus": "In Review",
    "bomStatus": "Complete",
    "routingStatus": "Pending",
    "progress": 53,
    "createdDate": "2023-07-07",
    "notes": "In Review artwork, Complete BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-134",
    "customer": "Vedanta Limited",
    "job": "Luxury Gift Boxes",
    "sdoId": "SDO-2024-031",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant C",
    "artworkStatus": "Pending",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 44,
    "createdDate": "2023-05-26",
    "notes": "Pending artwork, Pending BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-135",
    "customer": "Crompton Greaves",
    "job": "Retail Display Boxes",
    "sdoId": "SDO-2024-086",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant A",
    "artworkStatus": "Pending",
    "bomStatus": "Clarification",
    "routingStatus": "Complete",
    "progress": 88,
    "createdDate": "2023-07-28",
    "notes": "Pending artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-136",
    "customer": "FAG Bearings",
    "job": "Auto Parts Packaging",
    "sdoId": "SDO-2024-089",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant C",
    "artworkStatus": "Clarification",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 85,
    "createdDate": "2023-08-27",
    "notes": "Clarification artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-137",
    "customer": "Tropicana India",
    "job": "Snack Packaging",
    "sdoId": "SDO-2024-068",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "artworkStatus": "Approved",
    "bomStatus": "Complete",
    "routingStatus": "Clarification",
    "progress": 75,
    "createdDate": "2023-11-06",
    "notes": "Approved artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-138",
    "customer": "SKF India",
    "job": "Auto Parts Packaging",
    "sdoId": "SDO-2024-090",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant A",
    "artworkStatus": "Pending",
    "bomStatus": "Clarification",
    "routingStatus": "Pending",
    "progress": 65,
    "createdDate": "2023-09-09",
    "notes": "Pending artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-139",
    "customer": "Reebok India",
    "job": "E-commerce Shipping Boxes",
    "sdoId": "SDO-2024-082",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant D",
    "artworkStatus": "Approved",
    "bomStatus": "Clarification",
    "routingStatus": "Pending",
    "progress": 42,
    "createdDate": "2023-08-10",
    "notes": "Approved artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-140",
    "customer": "Hero MotoCorp",
    "job": "Pharmaceutical Cartons",
    "sdoId": "SDO-2024-044",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "artworkStatus": "Clarification",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 81,
    "createdDate": "2023-12-28",
    "notes": "Clarification artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-141",
    "customer": "Samsung India",
    "job": "Beverage Cartons",
    "sdoId": "SDO-2024-131",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "artworkStatus": "In Review",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 47,
    "createdDate": "2023-08-20",
    "notes": "In Review artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-142",
    "customer": "Reebok India",
    "job": "Packaging Boxes",
    "sdoId": "SDO-2024-146",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant B",
    "artworkStatus": "Pending",
    "bomStatus": "Complete",
    "routingStatus": "Pending",
    "progress": 79,
    "createdDate": "2023-09-28",
    "notes": "Pending artwork, Complete BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-143",
    "customer": "Spencer's Retail",
    "job": "Auto Parts Packaging",
    "sdoId": "SDO-2024-021",
    "prePressPlant": "Prepress Hub 2",
    "productionPlant": "Plant B",
    "artworkStatus": "Approved",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 32,
    "createdDate": "2023-06-02",
    "notes": "Approved artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-144",
    "customer": "PepsiCo India",
    "job": "Appliance Cartons",
    "sdoId": "SDO-2024-013",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "artworkStatus": "In Review",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 57,
    "createdDate": "2023-11-01",
    "notes": "In Review artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-145",
    "customer": "Hitachi India",
    "job": "Delivery Cartons",
    "sdoId": "SDO-2024-025",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "artworkStatus": "In Review",
    "bomStatus": "Complete",
    "routingStatus": "Clarification",
    "progress": 73,
    "createdDate": "2023-05-21",
    "notes": "In Review artwork, Complete BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-146",
    "customer": "BHEL India",
    "job": "Delivery Cartons",
    "sdoId": "SDO-2024-116",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "artworkStatus": "Clarification",
    "bomStatus": "Clarification",
    "routingStatus": "Complete",
    "progress": 88,
    "createdDate": "2024-01-05",
    "notes": "Clarification artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-147",
    "customer": "Swiggy",
    "job": "Appliance Cartons",
    "sdoId": "SDO-2024-127",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "artworkStatus": "Pending",
    "bomStatus": "Clarification",
    "routingStatus": "Complete",
    "progress": 58,
    "createdDate": "2023-06-15",
    "notes": "Pending artwork, Clarification BOM",
    "mfReleased": true
  },
  {
    "id": "JDO-2024-148",
    "customer": "FAG Bearings",
    "job": "Electronic Device Boxes",
    "sdoId": "SDO-2024-024",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant D",
    "artworkStatus": "Pending",
    "bomStatus": "Clarification",
    "routingStatus": "Clarification",
    "progress": 52,
    "createdDate": "2024-01-14",
    "notes": "Pending artwork, Clarification BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-149",
    "customer": "MRF Tyres",
    "job": "Packaging Boxes",
    "sdoId": "SDO-2024-001",
    "prePressPlant": "Prepress Hub 1",
    "productionPlant": "Plant A",
    "artworkStatus": "In Review",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 61,
    "createdDate": "2023-05-10",
    "notes": "In Review artwork, Pending BOM",
    "mfReleased": false
  },
  {
    "id": "JDO-2024-150",
    "customer": "Adidas India",
    "job": "Beverage Cartons",
    "sdoId": "SDO-2024-146",
    "prePressPlant": "Prepress Hub 3",
    "productionPlant": "Plant C",
    "artworkStatus": "Approved",
    "bomStatus": "Pending",
    "routingStatus": "Complete",
    "progress": 51,
    "createdDate": "2023-10-29",
    "notes": "Approved artwork, Pending BOM",
    "mfReleased": false
  }
]
